import { brandTitleSvg } from './brand.mjs';

export function dashboardHtml() {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Light Remote MCP — Operator Wall</title><meta name="robots" content="noindex,nofollow,noarchive"><style>
:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:#080a0c;color:#d8dee7}*{box-sizing:border-box}body{margin:0;background:#080a0c}.wrap{max-width:1500px;margin:auto;padding:16px}.top{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center}.muted{color:#718096}.pill,.btn,input,select,.tab{border:1px solid #2b333d;background:#0e1216;color:#cfd7e3;border-radius:7px;padding:7px 9px;font:inherit}.brand-title{display:flex;align-items:center;gap:11px}.brand-title>span{display:flex;align-items:baseline;gap:7px}.brand-title strong{font-size:19px;color:#f3f4f6}.brand-title small{font-size:10px;letter-spacing:.16em;color:#718096}.brand-mark{flex:0 0 auto}.ok{color:#78d78b}.hold,.running{color:#e6c36b}.error{color:#ff8e8e}.timeout{color:#ffb56b}.controls,.tabs{display:flex;gap:7px;flex-wrap:wrap}.tabs{margin-top:12px;overflow:auto;flex-wrap:nowrap;padding-bottom:3px}.tab{cursor:pointer;white-space:nowrap}.tab.active{background:#1a222b;border-color:#61758a}.tab .state{margin-left:6px;font-size:11px}.sessionbox{margin-top:9px;border:1px solid #202832;background:#0a0e12;border-radius:8px;padding:9px 11px;font-size:12px;line-height:1.5}.term{margin-top:10px;border:1px solid #252d36;border-radius:10px;background:#050708;overflow:hidden}.head{padding:9px 12px;border-bottom:1px solid #20262d;display:flex;justify-content:space-between;gap:10px}#jobs{max-height:78vh;overflow:auto;padding:8px}.job{border:1px solid #171d23;border-radius:8px;margin:7px 0;background:#090c0f}.job.hidden{display:none}.jh{display:grid;grid-template-columns:86px 86px 1fr auto;gap:10px;padding:9px 10px;align-items:center;border-bottom:1px solid #151a20}.meta{padding:8px 10px;color:#8390a1;font-size:12px;white-space:pre-wrap}pre{margin:0;padding:10px;white-space:pre-wrap;word-break:break-word;font-size:12px;line-height:1.45;max-height:46vh;overflow:auto}.stderr{color:#ffb0b0}.cmd{color:#d9c580}.actions,.topright{display:flex;gap:6px;align-items:center}.topright form{margin:0}.small{font-size:11px;padding:5px 7px}@media(max-width:800px){.wrap{padding:9px}.jh{grid-template-columns:70px 1fr}.jh>span:nth-child(2){display:none}.actions{grid-column:1/-1}.meta{font-size:11px}}
</style></head><body><div class="wrap"><div class="top"><div>${brandTitleSvg(44)}<div class="muted" style="margin-top:6px">operator wall · ARM hub · session lanes · full history on VPS disk</div></div><div class="topright"><span id="conn" class="pill">connecting…</span><button id="ownerProof" class="btn small" type="button">Owner code</button><span id="ownerProofValue" class="pill">—</span><button id="copyOwnerProof" class="btn small" type="button" disabled>Copy</button><form method="post" action="/auth/logout"><button class="btn small" type="submit">Logout</button></form></div></div>
<div id="devicebox" class="sessionbox muted">loading devices…</div>
<div id="tabs" class="tabs"></div><div id="sessionbox" class="sessionbox muted">loading sessions…</div>
<div class="controls" style="margin-top:9px"><input id="filter" placeholder="filter cwd / command / output"><select id="status"><option value="">all status</option><option>running</option><option>ok</option><option>error</option><option>timeout</option></select><button id="pause" class="btn">Pause</button><button id="copyVisible" class="btn">Copy visible</button></div>
<div class="term"><div class="head"><span>LIVE OPERATOR STREAM</span><span id="stats" class="muted">0 jobs</span></div><div id="jobs"></div></div>
<script>
const box=document.getElementById('jobs'),devicebox=document.getElementById('devicebox'),tabs=document.getElementById('tabs'),sessionbox=document.getElementById('sessionbox'),filter=document.getElementById('filter'),statusSel=document.getElementById('status'),conn=document.getElementById('conn'),stats=document.getElementById('stats'),ownerProofValue=document.getElementById('ownerProofValue'),copyOwnerProof=document.getElementById('copyOwnerProof');
const jobs=new Map(),sessions=new Map(),seenEvents=new Set(),seenOrder=[],dirtyJobs=new Set(),pendingKeys=new Set();
let paused=false,pending=[],selected='ALL',deviceRows=[],renderTimer=null,sessionRefreshTimer=null,sessionsInFlight=null,devicesInFlight=null,probeInFlight=false,catchupInFlight=false,ownerProofPlain='';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function short(v,n=10){v=String(v||'');return v.length>n?v.slice(0,n)+'…':v;}
function fmtRemaining(ms){ms=Math.max(0,Number(ms)||0);const m=Math.floor(ms/60000),h=Math.floor(m/60);return h?(h+'h '+(m%60)+'m'):(m+'m');}
function eventKey(e){return e&&e.id!=null&&e.at?String(e.id)+'@'+String(e.at):'';}
function eventSeen(e){const k=eventKey(e);return !!k&&seenEvents.has(k);}
function rememberEvent(e){const k=eventKey(e);if(!k||seenEvents.has(k))return;seenEvents.add(k);seenOrder.push(k);while(seenOrder.length>12000)seenEvents.delete(seenOrder.shift());}
function renderDevices(){if(!deviceRows.length){devicebox.textContent='no registered devices';return;}devicebox.innerHTML=deviceRows.map(d=>{const c=d.connection||{},connected=c.state==='connected',cloud='<span class="'+(connected?'ok':'hold')+'">cloud '+esc(c.state||'dormant')+'</span>',remaining=connected&&c.remainingMs!=null?' · lease '+esc(fmtRemaining(c.remainingMs)):'';return '<b>'+esc(d.displayName||d.deviceId)+'</b> · <span class="'+esc(d.state==='online'?'ok':'muted')+'">'+esc(d.state||'unknown')+'</span> · '+cloud+remaining+' · node '+esc((d.nodeId||'').toUpperCase())+' · '+esc(d.platform||'unknown')+'/'+esc(d.architecture||'unknown')+' · sessions '+esc(d.activeSessions||0)+' · agent '+esc(d.agentVersion||'unknown')+(d.policy?' · <a href="/device-policy?id='+encodeURIComponent(d.deviceId)+'">Policy</a>':'' );}).join('<br>');}
function jobText(j){return ['['+(j.status||'running')+'] '+j.jobId,'node: '+(j.nodeId||'arm'),'session: '+(j.sessionId||''),'agent: '+(j.agentId||''),'request: '+(j.requestId||''),'cwd: '+(j.cwd||''),'command:\\n'+(j.script||''),j.stdout?'stdout:\\n'+j.stdout:'',j.stderr?'stderr:\\n'+j.stderr:'',j.exitCode!=null?'exit: '+j.exitCode:'',j.durationMs!=null?'duration_ms: '+j.durationMs:''].filter(Boolean).join('\\n');}
function liveSessions(){return [...sessions.values()].filter(s=>s.state==='active'||s.state==='hold').sort((a,b)=>a.createdAt-b.createdAt);}
function nodeKey(nodeId){return 'NODE:'+String(nodeId||'arm');}
function selectedNodeId(){return selected.startsWith('NODE:')?selected.slice(5):null;}
function renderTabs(){const live=liveSessions(),nodes=[...new Set([...deviceRows.map(d=>d.nodeId||'arm'),...live.map(s=>s.nodeId||'arm')])].sort();if(selected!=='ALL'&&!live.some(s=>s.sessionId===selected)&&!nodes.some(n=>nodeKey(n)===selected))selected='ALL';tabs.innerHTML='';const all=document.createElement('button');all.className='tab '+(selected==='ALL'?'active':'');all.textContent='ALL · '+live.length;all.onclick=()=>{selected='ALL';renderTabs();applyFilter();};tabs.appendChild(all);for(const n of nodes){const b=document.createElement('button'),count=live.filter(s=>(s.nodeId||'arm')===n).length;b.className='tab '+(selected===nodeKey(n)?'active':'');b.textContent='NODE '+n.toUpperCase()+' · '+count;b.onclick=()=>{selected=nodeKey(n);renderTabs();applyFilter();};tabs.appendChild(b);}for(const s of live){const b=document.createElement('button');b.className='tab '+(selected===s.sessionId?'active':'');b.innerHTML=esc((s.nodeId||'arm').toUpperCase()+' · '+(s.label||short(s.sessionId,12)))+' <span class="state '+esc(s.state)+'">'+esc(s.state)+'</span>';b.onclick=()=>{selected=s.sessionId;renderTabs();applyFilter();};tabs.appendChild(b);}renderSessionBox();}
function renderSessionBox(){if(selected==='ALL'){const byNode={};for(const s of liveSessions())byNode[s.nodeId||'arm']=(byNode[s.nodeId||'arm']||0)+1;sessionbox.textContent='hub ARM · live sessions '+liveSessions().length+' · '+Object.entries(byNode).map(([n,c])=>n.toUpperCase()+' '+c).join(' · ')+' · target 1–5';return;}const nodeId=selectedNodeId();if(nodeId){const live=liveSessions().filter(s=>(s.nodeId||'arm')===nodeId),device=deviceRows.find(d=>(d.nodeId||'arm')===nodeId),state=device?.state||'unknown';sessionbox.innerHTML='<b>NODE '+esc(nodeId.toUpperCase())+'</b> · <span class="'+esc(state==='online'?'ok':'muted')+'">'+esc(state)+'</span><br>live sessions '+esc(live.length)+' · device '+esc(device?.displayName||device?.deviceId||'unregistered')+' · '+esc(device?.platform||'unknown')+'/'+esc(device?.architecture||'unknown');return;}const s=sessions.get(selected);if(!s){sessionbox.textContent='session unavailable';return;}const graceMin=(s.graceMs||s.leaseMs)?Math.round((s.graceMs||s.leaseMs)/60000):0;sessionbox.innerHTML='<b>'+esc(s.label||s.sessionId)+'</b> · node '+esc((s.nodeId||'arm').toUpperCase())+' · '+esc(s.state)+'<br>session '+esc(s.sessionId)+' · agent '+esc(short(s.agentId,18))+' · workspace '+esc(s.workspace||'')+'<br>reconnect grace '+esc(s.gracePreset||s.leasePreset||'default')+(graceMin?' · '+esc(graceMin)+'m':'')+' · calls '+esc(s.stats?.toolCalls||0)+' · exec '+esc(s.stats?.execCalls||0)+' · active jobs '+esc(s.activeJobs?.length||0)+' · reconnects '+esc(s.reconnectCount||0);}
function applyFilter(){const q=filter.value.toLowerCase(),st=statusSel.value,nodeId=selectedNodeId();let visible=0;for(const [id,j] of jobs){const el=document.getElementById('j-'+id);if(!el)continue;const lane=selected==='ALL'||(nodeId?(j.nodeId||'arm')===nodeId:j.sessionId===selected);const hay=q?[j.cwd,j.script,j.stdout,j.stderr,j.note,id,j.sessionId,j.agentId,j.nodeId].join(' ').toLowerCase():'';const hide=!lane||(q&&!hay.includes(q))||(st&&j.status!==st);el.classList.toggle('hidden',!!hide);if(!hide)visible++;}stats.textContent=visible+' visible / '+jobs.size+' jobs';}
function render(j){let el=document.getElementById('j-'+j.jobId);if(!el){el=document.createElement('div');el.className='job';el.id='j-'+j.jobId;box.prepend(el);while(box.children.length>2500)box.lastChild.remove();}el.innerHTML='<div class="jh"><span class="'+esc(j.status||'running')+'">'+esc(j.status||'running')+'</span><span class="muted">'+esc(new Date(j.at||j.startedAt||Date.now()).toLocaleTimeString())+'</span><span>'+esc((j.script||'').split('\\n')[0]||j.jobId)+'</span><span class="actions"><button class="btn small" data-copy="cmd">Copy cmd</button><button class="btn small" data-copy="out">Copy output</button><button class="btn small" data-copy="raw">Copy raw</button></span></div><div class="meta">'+esc((j.nodeId||'arm').toUpperCase())+' · session '+esc(j.sessionId||'')+' · agent '+esc(short(j.agentId,18))+' · '+esc(j.cwd||'')+'</div><pre class="cmd">'+esc(j.script||'')+'</pre><pre>'+esc(j.stdout||'')+'</pre><pre class="stderr">'+esc(j.stderr||'')+'</pre>';el.querySelector('[data-copy="cmd"]').onclick=()=>navigator.clipboard.writeText(j.script||'');el.querySelector('[data-copy="out"]').onclick=()=>navigator.clipboard.writeText((j.stdout||'')+(j.stderr?'\\n[stderr]\\n'+j.stderr:''));el.querySelector('[data-copy="raw"]').onclick=()=>navigator.clipboard.writeText(jobText(j));}
function flushRenders(){renderTimer=null;const ids=[...dirtyJobs];dirtyJobs.clear();for(const id of ids){const j=jobs.get(id);if(j)render(j);}applyFilter();}
function scheduleRender(id){if(id)dirtyJobs.add(id);if(renderTimer)return;renderTimer=setTimeout(flushRenders,75);}
function scheduleSessionRefresh(delay=150){if(sessionRefreshTimer)return;sessionRefreshTimer=setTimeout(()=>{sessionRefreshTimer=null;refreshSessions();},delay);}
function ingest(e,opts={}){const queue=opts.queue!==false,doRender=opts.render!==false,refresh=opts.refresh!==false;if(!e||eventSeen(e))return false;const k=eventKey(e);if(paused&&queue){if(!k||!pendingKeys.has(k)){pending.push(e);if(k)pendingKeys.add(k);}return false;}let j=e.jobId?jobs.get(e.jobId):null;if(e.type==='job_started'){if(!j){j={jobId:e.jobId,requestId:e.requestId,sessionId:e.sessionId,agentId:e.agentId,nodeId:e.nodeId||'arm',status:'running',cwd:e.cwd,script:e.script,note:e.note,stdout:'',stderr:'',at:e.at};jobs.set(e.jobId,j);}else{Object.assign(j,{requestId:e.requestId||j.requestId,sessionId:e.sessionId||j.sessionId,agentId:e.agentId||j.agentId,nodeId:e.nodeId||j.nodeId,cwd:e.cwd??j.cwd,script:e.script??j.script,note:e.note??j.note,at:e.at||j.at});}}else if(e.type==='stdout'||e.type==='stderr'){if(!j)return false;j[e.type]+=(e.chunk||'');}else if(e.type==='job_finished'){if(!j)return false;Object.assign(j,{status:e.status,exitCode:e.exitCode,durationMs:e.durationMs});}else if(e.type&&e.type.startsWith('device_')){refreshDevices();rememberEvent(e);return true;}else if(e.type&&e.type.startsWith('session_')){if(refresh)scheduleSessionRefresh();rememberEvent(e);return true;}else{rememberEvent(e);return true;}rememberEvent(e);if(doRender&&j)scheduleRender(j.jobId);return true;}
async function refreshDevices(){if(devicesInFlight)return devicesInFlight;devicesInFlight=(async()=>{try{const r=await fetch('/api/devices',{cache:'no-store'}),d=await r.json();deviceRows=(Array.isArray(d.devices)?d.devices:[]).filter(row=>row&&row.state!=='revoked');renderDevices();renderTabs();applyFilter();}catch{devicebox.textContent='device metadata unavailable';}finally{devicesInFlight=null;}})();return devicesInFlight;}
async function refreshSessions(){if(sessionsInFlight)return sessionsInFlight;sessionsInFlight=(async()=>{try{const r=await fetch('/api/sessions',{cache:'no-store'}),d=await r.json();sessions.clear();for(const s of (d.sessions||[]))sessions.set(s.sessionId,s);renderTabs();applyFilter();}catch{sessionbox.textContent='session metadata unavailable';}finally{sessionsInFlight=null;}})();return sessionsInFlight;}
async function loadActivity(limit=5000){try{const r=await fetch('/api/activity?limit='+limit,{cache:'no-store'}),d=await r.json();for(const e of (d.events||[]))ingest(e,{queue:false,render:true,refresh:false});scheduleSessionRefresh(0);}catch{}}
async function catchUpActivity(){if(catchupInFlight)return catchupInFlight;catchupInFlight=(async()=>{try{const r=await fetch('/api/activity?limit=500',{cache:'no-store'}),d=await r.json();let touchedSession=false;for(const e of (d.events||[])){const wasSession=!!(e.type&&e.type.startsWith('session_'));if(ingest(e,{queue:true,render:true,refresh:false})&&wasSession)touchedSession=true;}if(touchedSession)scheduleSessionRefresh();}catch{}finally{catchupInFlight=null;}})();return catchupInFlight;}
async function probeActivityHead(){if(document.hidden||paused||probeInFlight)return;probeInFlight=true;try{const r=await fetch('/api/activity?limit=1',{cache:'no-store'}),d=await r.json(),head=(d.events||[])[0];if(head&&!eventSeen(head))await catchUpActivity();}catch{}finally{probeInFlight=false;}}
const es=new EventSource('/events');
es.onopen=()=>{conn.textContent='live';conn.className='pill ok';};
es.onerror=()=>{conn.textContent='reconnecting';conn.className='pill running';};
es.addEventListener('activity',ev=>{try{ingest(JSON.parse(ev.data));}catch{}});
refreshDevices();refreshSessions();loadActivity();setInterval(probeActivityHead,1000);setInterval(()=>{if(!document.hidden)refreshDevices();},30000);
filter.oninput=applyFilter;statusSel.onchange=applyFilter;
document.getElementById('ownerProof').onclick=async()=>{try{const r=await fetch('/api/account-owner-proof',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'owner_proof_unavailable');ownerProofPlain=String(j.proof?.code||'');ownerProofValue.textContent=ownerProofPlain||'—';copyOwnerProof.disabled=!ownerProofPlain;}catch(e){ownerProofPlain='';ownerProofValue.textContent='unavailable';copyOwnerProof.disabled=true;alert(e.message);}};
copyOwnerProof.onclick=async()=>{if(!ownerProofPlain)return;try{await navigator.clipboard.writeText(ownerProofPlain);const prior=copyOwnerProof.textContent;copyOwnerProof.textContent='Copied';setTimeout(()=>copyOwnerProof.textContent=prior,900);}catch{alert('Unable to copy owner code');}};
document.getElementById('pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Resume':'Pause';if(!paused){const q=pending;pending=[];pendingKeys.clear();for(const item of q)ingest(item,{queue:false});probeActivityHead();}};
document.getElementById('copyVisible').onclick=()=>navigator.clipboard.writeText([...jobs.values()].filter(j=>{const el=document.getElementById('j-'+j.jobId);return el&&!el.classList.contains('hidden');}).map(jobText).join('\\n\\n---\\n\\n'));

</script></div></body></html>`;
}
