export function dashboardHtml() {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GPT VPS Operator Wall</title><meta name="robots" content="noindex,nofollow,noarchive"><style>
:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:#080a0c;color:#d8dee7}*{box-sizing:border-box}body{margin:0;background:#080a0c}.wrap{max-width:1500px;margin:auto;padding:16px}.top{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center}.muted{color:#718096}.pill,.btn,input,select,.tab{border:1px solid #2b333d;background:#0e1216;color:#cfd7e3;border-radius:7px;padding:7px 9px;font:inherit}.ok{color:#78d78b}.hold,.running{color:#e6c36b}.error{color:#ff8e8e}.timeout{color:#ffb56b}.controls,.tabs{display:flex;gap:7px;flex-wrap:wrap}.tabs{margin-top:12px;overflow:auto;flex-wrap:nowrap;padding-bottom:3px}.tab{cursor:pointer;white-space:nowrap}.tab.active{background:#1a222b;border-color:#61758a}.tab .state{margin-left:6px;font-size:11px}.sessionbox{margin-top:9px;border:1px solid #202832;background:#0a0e12;border-radius:8px;padding:9px 11px;font-size:12px;line-height:1.5}.term{margin-top:10px;border:1px solid #252d36;border-radius:10px;background:#050708;overflow:hidden}.head{padding:9px 12px;border-bottom:1px solid #20262d;display:flex;justify-content:space-between;gap:10px}#jobs{max-height:78vh;overflow:auto;padding:8px}.job{border:1px solid #171d23;border-radius:8px;margin:7px 0;background:#090c0f}.job.hidden{display:none}.jh{display:grid;grid-template-columns:86px 86px 1fr auto;gap:10px;padding:9px 10px;align-items:center;border-bottom:1px solid #151a20}.meta{padding:8px 10px;color:#8390a1;font-size:12px;white-space:pre-wrap}pre{margin:0;padding:10px;white-space:pre-wrap;word-break:break-word;font-size:12px;line-height:1.45;max-height:46vh;overflow:auto}.stderr{color:#ffb0b0}.cmd{color:#d9c580}.actions{display:flex;gap:6px}.small{font-size:11px;padding:5px 7px}@media(max-width:800px){.wrap{padding:9px}.jh{grid-template-columns:70px 1fr}.jh>span:nth-child(2){display:none}.actions{grid-column:1/-1}.meta{font-size:11px}}
</style></head><body><div class="wrap"><div class="top"><div><h1 style="font-size:19px;margin:0">GPT VPS Operator Wall</h1><div class="muted">read-only · ARM hub · session lanes · full history on VPS disk</div></div><span id="conn" class="pill">connecting…</span></div>
<div id="tabs" class="tabs"></div><div id="sessionbox" class="sessionbox muted">loading sessions…</div>
<div class="controls" style="margin-top:9px"><input id="filter" placeholder="filter cwd / command / output"><select id="status"><option value="">all status</option><option>running</option><option>ok</option><option>error</option><option>timeout</option></select><button id="pause" class="btn">Pause</button><button id="copyVisible" class="btn">Copy visible</button></div>
<div class="term"><div class="head"><span>LIVE OPERATOR STREAM</span><span id="stats" class="muted">0 jobs</span></div><div id="jobs"></div></div>
<script>
const box=document.getElementById('jobs'),tabs=document.getElementById('tabs'),sessionbox=document.getElementById('sessionbox'),filter=document.getElementById('filter'),statusSel=document.getElementById('status'),conn=document.getElementById('conn'),stats=document.getElementById('stats');
const jobs=new Map(),sessions=new Map();let paused=false,pending=[],selected='ALL';
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}function short(v,n=10){v=String(v||'');return v.length>n?v.slice(0,n)+'…':v;}
function jobText(j){return ['['+(j.status||'running')+'] '+j.jobId,'node: '+(j.nodeId||'arm'),'session: '+(j.sessionId||''),'agent: '+(j.agentId||''),'request: '+(j.requestId||''),'cwd: '+(j.cwd||''),'command:\n'+(j.script||''),j.stdout?'stdout:\n'+j.stdout:'',j.stderr?'stderr:\n'+j.stderr:'',j.exitCode!=null?'exit: '+j.exitCode:'',j.durationMs!=null?'duration_ms: '+j.durationMs:''].filter(Boolean).join('\n');}
function liveSessions(){return [...sessions.values()].filter(s=>s.state==='active'||s.state==='hold').sort((a,b)=>a.createdAt-b.createdAt);}function renderTabs(){const live=liveSessions();if(selected!=='ALL'&&!live.some(s=>s.sessionId===selected))selected='ALL';tabs.innerHTML='';const all=document.createElement('button');all.className='tab '+(selected==='ALL'?'active':'');all.textContent='ALL · '+live.length;all.onclick=()=>{selected='ALL';renderTabs();applyFilter();};tabs.appendChild(all);for(const s of live){const b=document.createElement('button');b.className='tab '+(selected===s.sessionId?'active':'');b.innerHTML=esc((s.nodeId||'arm').toUpperCase()+' · '+(s.label||short(s.sessionId,12)))+' <span class="state '+esc(s.state)+'">'+esc(s.state)+'</span>';b.onclick=()=>{selected=s.sessionId;renderTabs();applyFilter();};tabs.appendChild(b);}renderSessionBox();}
function renderSessionBox(){if(selected==='ALL'){const byNode={};for(const s of liveSessions())byNode[s.nodeId||'arm']=(byNode[s.nodeId||'arm']||0)+1;sessionbox.textContent='hub ARM · live sessions '+liveSessions().length+' · '+Object.entries(byNode).map(([n,c])=>n.toUpperCase()+' '+c).join(' · ')+' · target 1–5';return;}const s=sessions.get(selected);if(!s){sessionbox.textContent='session unavailable';return;}sessionbox.innerHTML='<b>'+esc(s.label||s.sessionId)+'</b> · node '+esc((s.nodeId||'arm').toUpperCase())+' · '+esc(s.state)+'<br>session '+esc(s.sessionId)+' · agent '+esc(short(s.agentId,18))+' · workspace '+esc(s.workspace||'')+'<br>calls '+esc(s.stats?.toolCalls||0)+' · exec '+esc(s.stats?.execCalls||0)+' · active jobs '+esc(s.activeJobs?.length||0)+' · reconnects '+esc(s.reconnectCount||0);}
function applyFilter(){const q=filter.value.toLowerCase(),st=statusSel.value;let visible=0;for(const [id,j] of jobs){const el=document.getElementById('j-'+id);if(!el)continue;const lane=selected==='ALL'||j.sessionId===selected;const hay=[j.cwd,j.script,j.stdout,j.stderr,j.note,id,j.sessionId,j.agentId,j.nodeId].join(' ').toLowerCase();const hide=!lane||(q&&!hay.includes(q))||(st&&j.status!==st);el.classList.toggle('hidden',!!hide);if(!hide)visible++;}stats.textContent=visible+' visible / '+jobs.size+' jobs';}
function render(j){let el=document.getElementById('j-'+j.jobId);if(!el){el=document.createElement('div');el.className='job';el.id='j-'+j.jobId;box.prepend(el);while(box.children.length>2500)box.lastChild.remove();}el.innerHTML='<div class="jh"><span class="'+esc(j.status||'running')+'">'+esc(j.status||'running')+'</span><span class="muted">'+esc(new Date(j.at||j.startedAt||Date.now()).toLocaleTimeString())+'</span><span>'+esc((j.script||'').split('\n')[0]||j.jobId)+'</span><span class="actions"><button class="btn small" data-copy="cmd">Copy cmd</button><button class="btn small" data-copy="out">Copy output</button><button class="btn small" data-copy="raw">Copy raw</button></span></div><div class="meta">'+esc((j.nodeId||'arm').toUpperCase())+' · session '+esc(j.sessionId||'')+' · agent '+esc(short(j.agentId,18))+' · '+esc(j.cwd||'')+'</div><pre class="cmd">'+esc(j.script||'')+'</pre><pre>'+esc(j.stdout||'')+'</pre><pre class="stderr">'+esc(j.stderr||'')+'</pre>';el.querySelector('[data-copy="cmd"]').onclick=()=>navigator.clipboard.writeText(j.script||'');el.querySelector('[data-copy="out"]').onclick=()=>navigator.clipboard.writeText((j.stdout||'')+(j.stderr?'\n[stderr]\n'+j.stderr:''));el.querySelector('[data-copy="raw"]').onclick=()=>navigator.clipboard.writeText(jobText(j));applyFilter();}
function ingest(e){if(paused){pending.push(e);return;}let j=jobs.get(e.jobId);if(e.type==='job_started'){j={jobId:e.jobId,requestId:e.requestId,sessionId:e.sessionId,agentId:e.agentId,nodeId:e.nodeId||'arm',status:'running',cwd:e.cwd,script:e.script,note:e.note,stdout:'',stderr:'',at:e.at};jobs.set(e.jobId,j);}else if(j&&e.type==='stdout'){j.stdout+=(e.chunk||'');}else if(j&&e.type==='stderr'){j.stderr+=(e.chunk||'');}else if(j&&e.type==='job_finished'){Object.assign(j,{status:e.status,exitCode:e.exitCode,durationMs:e.durationMs});}else if(e.type&&e.type.startsWith('session_')){refreshSessions();return;}else return;render(j);}
async function refreshSessions(){try{const r=await fetch('/api/sessions',{cache:'no-store'}),d=await r.json();sessions.clear();for(const s of (d.sessions||[]))sessions.set(s.sessionId,s);renderTabs();applyFilter();}catch{sessionbox.textContent='session metadata unavailable';}}
fetch('/api/activity?limit=5000',{cache:'no-store'}).then(r=>r.json()).then(j=>{for(const e of (j.events||[]))ingest(e);});refreshSessions();setInterval(refreshSessions,5000);
const es=new EventSource('/events');es.onopen=()=>{conn.textContent='live';conn.className='pill ok'};es.onerror=()=>{conn.textContent='reconnecting';conn.className='pill running'};es.addEventListener('activity',ev=>{try{ingest(JSON.parse(ev.data))}catch{}});filter.oninput=applyFilter;statusSel.onchange=applyFilter;document.getElementById('pause').onclick=e=>{paused=!paused;e.target.textContent=paused?'Resume':'Pause';if(!paused){const q=pending;pending=[];q.forEach(ingest);}};document.getElementById('copyVisible').onclick=()=>navigator.clipboard.writeText([...jobs.values()].filter(j=>{const el=document.getElementById('j-'+j.jobId);return el&&!el.classList.contains('hidden');}).map(jobText).join('\n\n---\n\n'));
</script></div></body></html>`;
}
