export function enrollmentApprovalHtml(enrollmentId) {
  const safeId = JSON.stringify(enrollmentId);
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approve device</title><style>:root{color-scheme:dark;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:#080a0c;color:#d8dee7}body{margin:0;padding:24px}.card{max-width:720px;margin:auto;border:1px solid #29313a;border-radius:12px;padding:20px;background:#0b0f13}.muted{color:#82909f}.grid{display:grid;grid-template-columns:160px 1fr;gap:8px 12px}input,button{width:100%;box-sizing:border-box;margin-top:8px;padding:10px;border-radius:7px;border:1px solid #34404b;background:#10161c;color:inherit}label{display:block;margin-top:14px}.caps label{display:inline-flex;width:auto;margin:6px 12px 0 0;gap:6px}.caps input{width:auto;margin:0}pre{white-space:pre-wrap;word-break:break-word}button{cursor:pointer}</style></head><body><main class="card"><h1>Device enrollment</h1><div id="status" class="muted">Loading request…</div><div id="details"></div><form id="approve" hidden><label>One-time device code<input name="code" required autocomplete="one-time-code" placeholder="ABCD-EFGH"></label><label>Device name<input name="displayName" id="displayName" required></label><label>Policy profile<input name="policyProfile" id="policyProfile" required></label><div><strong>Approved capabilities</strong><div id="caps" class="caps"></div></div><button type="submit">Approve this device</button></form></main><script>
const enrollmentId=${safeId}; const status=document.getElementById('status'), details=document.getElementById('details'), form=document.getElementById('approve');
async function load(){const r=await fetch('/api/enrollments',{cache:'no-store'});if(!r.ok)throw new Error('Cannot load enrollments');const j=await r.json();const row=(j.pending||[]).find(x=>x.enrollmentId===enrollmentId);if(!row){status.textContent='Enrollment request not found or expired.';return;}status.textContent='Pending approval';details.innerHTML='<div class="grid"><b>Fingerprint</b><span>'+esc(row.fingerprintSummary)+'</span><b>Key SHA-256</b><span>'+esc(row.publicKeySha256)+'</span><b>Platform</b><span>'+esc(row.platform)+' / '+esc(row.architecture)+'</span><b>Agent</b><span>'+esc(row.agentVersion)+'</span></div>';document.getElementById('displayName').value=row.displayName;document.getElementById('policyProfile').value=row.requestedPolicy;document.getElementById('caps').innerHTML=row.requestedCapabilities.map(c=>'<label><input type="checkbox" value="'+esc(c)+'" checked> '+esc(c)+'</label>').join('');form.hidden=false;}
function esc(v){return String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}
form.addEventListener('submit',async e=>{e.preventDefault();const approvedCapabilities=[...document.querySelectorAll('#caps input:checked')].map(x=>x.value);const body={code:new FormData(form).get('code'),displayName:new FormData(form).get('displayName'),policyProfile:new FormData(form).get('policyProfile'),approvedCapabilities};const r=await fetch('/api/enrollments/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){status.textContent='Approval failed: '+(j.error||'unknown');return;}status.textContent='Approved. The device may finish enrollment now.';form.hidden=true;details.innerHTML+='<pre>'+esc(JSON.stringify({deviceId:j.approval?.deviceId||j.device?.deviceId,state:j.device?.state},null,2))+'</pre>';});
load().catch(e=>status.textContent=e.message);
</script></body></html>`;
}
