import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import {UPDATE_CODES} from '../../lib/update-contract.mjs';
import {updateRuntimePaths,writeStatus,writeReport,clearRequest,clearCheckRequest,beginTransaction,clearTransaction,waitForCoreAck,finalizeHelperFromCore,helperVersion,updateCodeForError} from './update-lifeboat.mjs';

const ROOT=process.env.LIGHT_REMOTE_ROOT||'/Library/Application Support/Light Remote';
const CURRENT=path.join(ROOT,'current'), RELEASES=path.join(ROOT,'releases');
const PATHS=updateRuntimePaths(ROOT,process.env.LIGHT_REMOTE_UPDATE_STATE_DIR||path.join(ROOT,'update-runtime'));
const LOCK=path.join(PATHS.updaterRoot,'.update.lock');
const PUBLIC_KEY=process.env.GPT_OPERATOR_UPDATE_PUBLIC_KEY||path.join(ROOT,'update-public.pem');
const MANIFEST_URL=process.env.GPT_OPERATOR_UPDATE_MANIFEST_URL||'https://raw.githubusercontent.com/n8n2erpnext/light-remote-mcp/main/channels/beta/client-update.json';
const SIGNATURE_URL=process.env.GPT_OPERATOR_UPDATE_SIGNATURE_URL||'https://raw.githubusercontent.com/n8n2erpnext/light-remote-mcp/main/channels/beta/client-update.json.sig';
const AGENT_LABEL='com.lightremote.agent', TRAY_LABEL='com.lightremote.tray';

function fail(message,code=UPDATE_CODES.UNKNOWN){const error=new Error(message);error.code=code;throw error;}
function coded(error,code){const next=new Error(error?.message||'update_failed');next.code=code;next.cause=error;return next;}
function reportId(){return `ur_${crypto.randomBytes(14).toString('base64url')}`;}
function status(state,currentVersion,targetVersion=null,code=null){return writeStatus(PATHS,{state,currentVersion,targetVersion,helperVersion:helperVersion(PATHS)||currentVersion,code});}
function report(input){return writeReport(PATHS,{reportId:reportId(),helperVersion:helperVersion(PATHS)||currentVersion(),platform:platformKey(),...input});}
function updaterSelfTest(){const source=fileURLToPath(import.meta.url),contract=fileURLToPath(new URL('../../lib/update-contract.mjs',import.meta.url));if(!fs.existsSync(source)||!fs.existsSync(contract))return false;console.log(JSON.stringify({ok:true,runtime:'independent-updater',source,helperRoot:PATHS.updaterRoot,stateDir:PATHS.stateDir,helperVersion:helperVersion(PATHS)}));console.log('updater_selftest=PASS');return true;}
function run(file,args,{allowFailure=false}={}){ const r=spawnSync(file,args,{encoding:'utf8'}); if(!allowFailure&&r.status!==0) fail(`${path.basename(file)}_failed:${r.status}:${String(r.stderr||r.stdout).trim()}`); return r; }
function platformKey(){ if(process.platform!=='darwin') fail('macos_only'); if(process.arch==='x64') return 'macos-x64'; if(process.arch==='arm64') return 'macos-arm64'; fail(`unsupported_arch:${process.arch}`); }
function parseVersion(value){ const m=String(value||'').replace(/^v/,'').match(/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z.-]+)?$/); return m?{core:m.slice(1,4).map(Number),pre:m[4]?m[4].split('.'):[]}:null; }
function comparePre(a,b){ if(!a.length&&!b.length)return 0;if(!a.length)return 1;if(!b.length)return-1;for(let i=0;i<Math.max(a.length,b.length);i++){if(i>=a.length)return-1;if(i>=b.length)return 1;const x=a[i],y=b[i],xn=/^\d+$/.test(x),yn=/^\d+$/.test(y);if(xn&&yn){const d=Number(x)-Number(y);if(d)return d>0?1:-1;}else if(xn!==yn)return xn?-1:1;else if(x!==y)return x>y?1:-1;}return 0; }
function newer(a,b){ const aa=parseVersion(a),bb=parseVersion(b);if(!aa||!bb)return false;for(let i=0;i<3;i++){if(aa.core[i]!==bb.core[i])return aa.core[i]>bb.core[i];}return comparePre(aa.pre,bb.pre)>0; }
async function download(url){ const r=await fetch(url,{signal:AbortSignal.timeout(30000)});if(r.status===404)return null;if(!r.ok)fail(`download_${r.status}`);return Buffer.from(await r.arrayBuffer()); }
function verifyManifest(bytes,signatureText){ const key=fs.readFileSync(PUBLIC_KEY,'utf8');let signature;try{signature=Buffer.from(String(signatureText||'').trim(),'base64');}catch{fail('invalid_manifest_signature_encoding');}if(!signature.length||!crypto.verify('sha256',bytes,key,signature))fail('invalid_manifest_signature'); }
function currentVersion(){ try{return JSON.parse(fs.readFileSync(path.join(CURRENT,'manifest.json'),'utf8')).version||'0.0.0';}catch{return'0.0.0';} }
function atomicCurrent(target){ const next=path.join(ROOT,`.current-${process.pid}`);fs.rmSync(next,{force:true});fs.symlinkSync(target,next);fs.renameSync(next,CURRENT); }
function consoleContext(){ const result=run('/usr/bin/stat',['-f','%Su','/dev/console'],{allowFailure:true});const user=String(result.stdout||'').trim();if(!user||['root','_mbsetupuser','loginwindow'].includes(user))return null;const id=run('/usr/bin/id',['-u',user],{allowFailure:true});const uid=Number(String(id.stdout||'').trim());return Number.isInteger(uid)&&uid>0?{user,uid}:null; }
function launch(ctx,args,{allowFailure=false}={}){ return run('/bin/launchctl',['asuser',String(ctx.uid),'/bin/launchctl',...args],{allowFailure}); }
function agentState(ctx){ if(!ctx)return{healthy:true,pid:0};const r=launch(ctx,['print',`gui/${ctx.uid}/${AGENT_LABEL}`],{allowFailure:true});const text=String(r.stdout||'');const match=text.match(/\bpid\s*=\s*(\d+)/);return{healthy:r.status===0&&/\bstate\s*=\s*running\b/.test(text)&&Number(match?.[1])>0,pid:Number(match?.[1])||0}; }
function restartAgent(ctx){ if(!ctx)return true;launch(ctx,['enable',`gui/${ctx.uid}/${AGENT_LABEL}`],{allowFailure:true});return launch(ctx,['kickstart','-k',`gui/${ctx.uid}/${AGENT_LABEL}`],{allowFailure:true}).status===0; }
function restartTray(ctx){ if(!ctx)return;launch(ctx,['enable',`gui/${ctx.uid}/${TRAY_LABEL}`],{allowFailure:true});launch(ctx,['kickstart','-k',`gui/${ctx.uid}/${TRAY_LABEL}`],{allowFailure:true}); }
async function stableAgent(ctx,timeoutMs=15000,stableMs=3000){ if(!ctx)return true;const deadline=Date.now()+timeoutMs;let healthySince=0;while(Date.now()<deadline){if(agentState(ctx).healthy){if(!healthySince)healthySince=Date.now();if(Date.now()-healthySince>=stableMs)return true;}else healthySince=0;await new Promise(r=>setTimeout(r,250));}return false; }
function pruneReleases(keep=3){ let rows=[];try{rows=fs.readdirSync(RELEASES,{withFileTypes:true}).filter(x=>x.isDirectory()&&!x.name.startsWith('.incoming-')).map(x=>({name:x.name,mtime:fs.statSync(path.join(RELEASES,x.name)).mtimeMs})).sort((a,b)=>b.mtime-a.mtime);}catch{return;}for(const row of rows.slice(keep)){const full=path.join(RELEASES,row.name);try{if(fs.realpathSync(CURRENT)===fs.realpathSync(full))continue;}catch{}fs.rmSync(full,{recursive:true,force:true});} }

async function main(){
  if(process.argv.includes('--self-test')){if(!updaterSelfTest())process.exitCode=1;return;}
  if(process.getuid?.()!==0)fail('updater_requires_root');fs.mkdirSync(RELEASES,{recursive:true,mode:0o755});fs.mkdirSync(PATHS.updaterRoot,{recursive:true,mode:0o755});fs.mkdirSync(PATHS.stateDir,{recursive:true,mode:0o755});
  const applyRequested=process.argv.includes('--apply')||fs.existsSync(PATHS.request);clearCheckRequest(PATHS);if(applyRequested)clearRequest(PATHS);
  let lockFd;try{lockFd=fs.openSync(LOCK,'wx',0o600);}catch(error){if(error.code==='EEXIST'){console.log('update_already_running');return;}throw error;}
  const fromVersion=currentVersion(),helperBefore=helperVersion(PATHS)||fromVersion;let targetVersion=null,phase='checking',reported=false;
  try{
    status('checking',fromVersion);let manifestBytes;try{manifestBytes=await download(MANIFEST_URL);}catch(error){throw coded(error,UPDATE_CODES.MANIFEST_FETCH);}if(!manifestBytes){status('idle',fromVersion);return;}
    let signatureBytes;try{signatureBytes=await download(SIGNATURE_URL);}catch(error){throw coded(error,UPDATE_CODES.MANIFEST_FETCH);}if(!signatureBytes)fail('update_signature_missing',UPDATE_CODES.MANIFEST_SIGNATURE);try{verifyManifest(manifestBytes,signatureBytes.toString('utf8'));}catch(error){throw coded(error,UPDATE_CODES.MANIFEST_SIGNATURE);}
    const manifest=JSON.parse(manifestBytes.toString('utf8'));if(manifest.schemaVersion!==1)fail('unsupported_update_manifest',UPDATE_CODES.MANIFEST_SIGNATURE);targetVersion=String(manifest.version||'');if(!newer(targetVersion,fromVersion)){status('idle',fromVersion);console.log(`up_to_date:${fromVersion}`);return;}if(!applyRequested){status('available',fromVersion,targetVersion);console.log(`update_available:${targetVersion}`);return;}
    phase='download_artifact';status('downloading',fromVersion,targetVersion);const artifact=manifest.artifacts?.[platformKey()];if(!artifact)fail(`artifact_missing:${platformKey()}`,UPDATE_CODES.ARTIFACT_MISSING);if(!/^[a-f0-9]{64}$/i.test(String(artifact.sha256||'')))fail('invalid_artifact_sha256',UPDATE_CODES.ARTIFACT_INTEGRITY);let archive;try{archive=await download(artifact.url);}catch(error){throw coded(error,UPDATE_CODES.ARTIFACT_MISSING);}if(!archive)fail('artifact_not_found',UPDATE_CODES.ARTIFACT_MISSING);const actual=crypto.createHash('sha256').update(archive).digest('hex');if((Number(artifact.size)>0&&archive.length!==Number(artifact.size))||!crypto.timingSafeEqual(Buffer.from(actual,'hex'),Buffer.from(String(artifact.sha256),'hex')))fail('artifact_integrity_mismatch',UPDATE_CODES.ARTIFACT_INTEGRITY);
    phase='stage_core';status('staging_core',fromVersion,targetVersion);const target=path.join(RELEASES,targetVersion),tmp=path.join(RELEASES,`.incoming-${targetVersion}-${process.pid}`);fs.rmSync(tmp,{recursive:true,force:true});fs.mkdirSync(tmp,{recursive:true,mode:0o755});const archiveFile=path.join(tmp,'package.tar.gz');fs.writeFileSync(archiveFile,archive,{mode:0o600});run('/usr/bin/tar',['-xzf',archiveFile,'-C',tmp]);fs.rmSync(archiveFile,{force:true});const packageRoot=path.join(tmp,'package');const packageManifest=JSON.parse(fs.readFileSync(path.join(packageRoot,'manifest.json'),'utf8'));if(packageManifest.version!==targetVersion)fail('package_version_mismatch',UPDATE_CODES.CORE_STAGE);fs.rmSync(target,{recursive:true,force:true});fs.renameSync(packageRoot,target);run('/usr/sbin/chown',['-R','root:wheel',target]);run('/bin/chmod',['-R','go-w',target]);fs.rmSync(tmp,{recursive:true,force:true});
    let previous=null;try{previous=fs.realpathSync(CURRENT);}catch{}if(!previous)fail('current_release_missing',UPDATE_CODES.CORE_STAGE);const tx=beginTransaction(PATHS,{fromVersion,targetVersion,helperVersion:helperBefore}),ctx=consoleContext();if(!ctx)fail('console_user_required',UPDATE_CODES.CORE_RESTART);phase='verify_core';status('installing_core',fromVersion,targetVersion);atomicCurrent(target);const healthy=restartAgent(ctx)&&await stableAgent(ctx),ack=healthy?await waitForCoreAck(PATHS,tx,{timeoutMs:15000}):null;
    if(!healthy||!ack){status('rolling_back',fromVersion,targetVersion,UPDATE_CODES.CORE_HEALTH);let rollbackHealthy=false;if(previous&&fs.existsSync(previous)){atomicCurrent(previous);rollbackHealthy=restartAgent(ctx)&&await stableAgent(ctx,18000,3000);}const code=rollbackHealthy?UPDATE_CODES.CORE_HEALTH:UPDATE_CODES.ROLLBACK_FAILED;report({outcome:rollbackHealthy?'rollback':'failed',code,phase:'verify_core',fromVersion,targetVersion,activeVersion:currentVersion(),rollback:{attempted:true,success:rollbackHealthy},detail:healthy?'core health acknowledgement timeout':'core service failed health gate'});reported=true;clearTransaction(PATHS);if(!rollbackHealthy)fail('update_rollback_failed',code);status('rollback',fromVersion,targetVersion,code);restartTray(ctx);return;}
    phase='finalize_helper';status('core_healthy',targetVersion,targetVersion);try{finalizeHelperFromCore(PATHS,target);}catch(error){const code=updateCodeForError(error,UPDATE_CODES.HELPER_FINALIZE);report({outcome:'failed',code,phase,fromVersion,targetVersion,activeVersion:targetVersion,rollback:{attempted:false,success:false},detail:error.message});reported=true;clearTransaction(PATHS);status('core_healthy_helper_old',targetVersion,targetVersion,code);restartTray(ctx);return;}
    clearTransaction(PATHS);pruneReleases();status('success',targetVersion,targetVersion);report({outcome:'success',phase:'complete',fromVersion,targetVersion,activeVersion:targetVersion,rollback:{attempted:false,success:false}});reported=true;restartTray(ctx);console.log(`updated:${fromVersion}->${targetVersion}`);
  } catch(error){if(!reported){const code=updateCodeForError(error,phase==='checking'?UPDATE_CODES.MANIFEST_FETCH:UPDATE_CODES.UNKNOWN);try{status('failed',currentVersion(),targetVersion,code);report({outcome:'failed',code,phase,fromVersion,targetVersion,activeVersion:currentVersion(),rollback:{attempted:false,success:false},detail:error.message});}catch{}}throw error;}
  finally{try{if(lockFd!=null)fs.closeSync(lockFd);}catch{}try{fs.rmSync(LOCK,{force:true});}catch{}}
}
function invokedAsMain(){const arg=process.argv[1];if(!arg)return false;try{return fs.realpathSync(arg)===fs.realpathSync(fileURLToPath(import.meta.url));}catch{return false;}}
if(invokedAsMain())main().catch(error=>{console.error(`update_failed:${error.message}`);process.exitCode=1;});
