#!/usr/bin/env node
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { deviceHeartbeatMessage } from '../lib/device-proof.mjs';

const VERSION='0.7.0-dev';
const DEFAULT_BASE=process.env.OPERATOR_AGENT_BASE_URL || 'https://gpt-vps-bridge.vercel.app';
const STATE_FILE=process.env.OPERATOR_AGENT_STATE || path.join(os.homedir(),'.config','gpt-operator-agent','device.json');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function sha256(value){return crypto.createHash('sha256').update(value).digest('hex');}
function parseArgs(argv){const out={_:[]};for(let i=0;i<argv.length;i++){const v=argv[i];if(!v.startsWith('--'))out._.push(v);else{const k=v.slice(2);if(['no-wait','reenroll'].includes(k))out[k]=true;else out[k]=argv[++i];}}return out;}
function readState(){try{return JSON.parse(fs.readFileSync(STATE_FILE,'utf8'));}catch{return null;}}
function writeState(state){const dir=path.dirname(STATE_FILE);fs.mkdirSync(dir,{recursive:true,mode:0o700});const tmp=`${STATE_FILE}.${process.pid}.tmp`;fs.writeFileSync(tmp,`${JSON.stringify(state,null,2)}\n`,{mode:0o600});fs.chmodSync(tmp,0o600);fs.renameSync(tmp,STATE_FILE);}
function ensureIdentity(state={}){if(state.identity?.privateKey&&state.identity?.publicIdentityKey)return state;const {publicKey,privateKey}=crypto.generateKeyPairSync('ed25519');const publicIdentityKey=publicKey.export({format:'der',type:'spki'}).toString('base64');return {...state,identity:{algorithm:'Ed25519',privateKey:privateKey.export({format:'der',type:'pkcs8'}).toString('base64'),publicIdentityKey,publicKeySha256:sha256(Buffer.from(publicIdentityKey,'base64')),createdAt:Date.now()}};}
function hasCommand(name){const cmd=process.platform==='win32'?'where':'sh';const args=process.platform==='win32'?[name]:['-lc',`command -v ${name.replace(/[^A-Za-z0-9._-]/g,'')}`];return spawnSync(cmd,args,{stdio:'ignore'}).status===0;}
function discoverCapabilities(){const caps=['filesystem'];if(hasCommand('git'))caps.push('git');if(hasCommand('node')||hasCommand('python3')||hasCommand('cargo'))caps.push('build-test');if(hasCommand('docker'))caps.push('docker');if(hasCommand('lxc'))caps.push('lxd');if(hasCommand('systemctl'))caps.push('systemctl');if(hasCommand('sudo'))caps.push('sudo-on-demand');return caps;}
function effectiveCapabilities(approved,denied){const deny=new Set(denied||[]);return (approved||[]).filter(x=>!deny.has(x)).sort();}
async function operator(base,action,payload){const r=await fetch(`${base.replace(/\/$/,'')}/api/operator`,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({action,payload}),signal:AbortSignal.timeout(15000)});const text=await r.text();let json;try{json=JSON.parse(text)}catch{json={raw:text}}if(!r.ok||!json.ok){const e=new Error(json.error||`http_${r.status}`);e.status=r.status;e.payload=json;throw e;}return json.upstream;}
function privateKey(state){return crypto.createPrivateKey({key:Buffer.from(state.identity.privateKey,'base64'),format:'der',type:'pkcs8'});}
function verifyEnrollment(state,enrollment){const cert=enrollment.certificate;if(!cert||cert.publicKeySha256!==state.identity.publicKeySha256||cert.deviceId!==enrollment.deviceId)throw new Error('device_certificate_identity_mismatch');const signer=crypto.createPublicKey({key:Buffer.from(enrollment.signer.publicKey,'base64'),format:'der',type:'spki'});if(!crypto.verify(null,Buffer.from(JSON.stringify(cert)),signer,Buffer.from(enrollment.certificateSignature,'base64url')))throw new Error('device_certificate_signature_invalid');return true;}
async function heartbeat(state,base,{persist=true}={}){if(!state.enrollment?.deviceId)throw new Error('device_not_enrolled');const capabilities=effectiveCapabilities(state.enrollment.approvedCapabilities,state.policy?.deniedCapabilities);const timestamp=Date.now(),nonce=crypto.randomBytes(18).toString('base64url');const message=deviceHeartbeatMessage({deviceId:state.enrollment.deviceId,timestamp,nonce,capabilities});const signature=crypto.sign(null,Buffer.from(message),privateKey(state)).toString('base64url');const upstream=await operator(base,'device-heartbeat',{deviceId:state.enrollment.deviceId,timestamp,nonce,capabilities,signature});state.lastHeartbeatAt=Date.now();state.effectiveCapabilities=capabilities;if(persist)writeState(state);return upstream.device;}
async function finishEnrollment(state,base,{wait=false}={}){const pending=state.pendingEnrollment;if(!pending?.enrollmentId||!pending?.pollToken)throw new Error('no_pending_enrollment');do{const upstream=await operator(base,'enrollment-poll',{enrollmentId:pending.enrollmentId,pollToken:pending.pollToken});const e=upstream.enrollment;if(e.state==='approved'){verifyEnrollment(state,e);state.enrollment={enrollmentId:e.enrollmentId,deviceId:e.deviceId,accountId:e.accountId,approvedCapabilities:e.approvedCapabilities,policyProfile:e.policyProfile,certificate:e.certificate,certificateSignature:e.certificateSignature,signer:e.signer,enrolledAt:Date.now()};delete state.pendingEnrollment;writeState(state);const device=await heartbeat(state,base);return {state:'approved',device};}if(e.state==='expired'||e.state==='replaced'){delete state.pendingEnrollment;writeState(state);return {state:e.state};}if(!wait)return {state:e.state,expiresAt:e.expiresAt};if(Date.now()>=pending.expiresAt){delete state.pendingEnrollment;writeState(state);return {state:'expired'};}await sleep(3000);}while(true);}
async function login(args){const base=args.base||DEFAULT_BASE;let state=ensureIdentity(readState()||{});if(state.enrollment?.deviceId&&!args.reenroll){const device=await heartbeat(state,base);console.log(JSON.stringify({ok:true,alreadyEnrolled:true,deviceId:state.enrollment.deviceId,state:device.state,effectiveCapabilities:state.effectiveCapabilities},null,2));return;}const discovered=discoverCapabilities();const denied=String(args.deny||'').split(',').map(x=>x.trim()).filter(Boolean);const requested=discovered.filter(x=>!denied.includes(x));if(!requested.length)throw new Error('all_discovered_capabilities_locally_denied');state.policy={deniedCapabilities:denied,localFinalDenyBoundary:true};const hostname=os.hostname();const upstream=await operator(base,'enrollment-begin',{publicIdentityKey:state.identity.publicIdentityKey,displayName:args.name||hostname,platform:os.platform(),architecture:os.arch(),agentVersion:VERSION,fingerprintSummary:`${hostname} / ${os.platform()} ${os.arch()} / key ${state.identity.publicKeySha256.slice(0,12)}`,capabilities:requested,policyProfile:args.policy||'default'});const e=upstream.enrollment;state.pendingEnrollment={enrollmentId:e.enrollmentId,pollToken:e.pollToken,activationUrl:e.activationUrl,expiresAt:e.expiresAt,requestedCapabilities:e.requestedCapabilities,requestedPolicy:e.requestedPolicy};writeState(state);console.log(`Activation URL: ${e.activationUrl}`);console.log(`Device code: ${e.deviceCode}`);console.log(`Expires in: ${e.expiresInSeconds}s`);if(args['no-wait'])return;console.log('Waiting for approval…');const result=await finishEnrollment(state,base,{wait:true});console.log(JSON.stringify({ok:result.state==='approved',enrollment:result.state,deviceId:state.enrollment?.deviceId||null,state:result.device?.state||null,effectiveCapabilities:state.effectiveCapabilities||[]},null,2));}
async function daemon(args){const base=args.base||DEFAULT_BASE;const state=readState();if(!state?.enrollment?.deviceId)throw new Error('device_not_enrolled');const heartbeatMs=Math.max(1000,Math.min(Number(process.env.OPERATOR_AGENT_HEARTBEAT_MS)||30000,300000));let stopped=false,wake=null,failures=0,lastPersist=0;const stop=()=>{stopped=true;if(wake)wake();};process.on('SIGTERM',stop);process.on('SIGINT',stop);const wait=ms=>new Promise(resolve=>{const timer=setTimeout(()=>{wake=null;resolve();},ms);wake=()=>{clearTimeout(timer);wake=null;resolve();};});console.log(JSON.stringify({event:'device_agent_started',deviceId:state.enrollment.deviceId,heartbeatMs}));while(!stopped){try{const persist=Date.now()-lastPersist>=300000;await heartbeat(state,base,{persist});if(persist)lastPersist=Date.now();failures=0;}catch(error){failures++;console.error(JSON.stringify({event:'device_heartbeat_failed',deviceId:state.enrollment.deviceId,error:error.message,status:error.status||null,failures}));}if(stopped)break;const delay=failures?Math.min(heartbeatMs*(2**Math.min(failures,4)),300000):heartbeatMs;await wait(delay);}writeState(state);console.log(JSON.stringify({event:'device_agent_stopped',deviceId:state.enrollment.deviceId}));}
async function status(){const state=readState();if(!state){console.log(JSON.stringify({ok:true,enrolled:false,stateFile:STATE_FILE},null,2));return;}console.log(JSON.stringify({ok:true,enrolled:Boolean(state.enrollment?.deviceId),deviceId:state.enrollment?.deviceId||null,accountId:state.enrollment?.accountId||null,pendingEnrollmentId:state.pendingEnrollment?.enrollmentId||null,publicKeySha256:state.identity?.publicKeySha256||null,policyProfile:state.enrollment?.policyProfile||state.pendingEnrollment?.requestedPolicy||null,approvedCapabilities:state.enrollment?.approvedCapabilities||[],deniedCapabilities:state.policy?.deniedCapabilities||[],effectiveCapabilities:state.effectiveCapabilities||[],lastHeartbeatAt:state.lastHeartbeatAt||null,stateFile:STATE_FILE,privateKeyStoredLocally:Boolean(state.identity?.privateKey)},null,2));}
const args=parseArgs(process.argv.slice(2)),command=args._[0]||'status';
try{if(command==='login')await login(args);else if(command==='poll'){const state=readState();if(!state)throw new Error('no_device_state');console.log(JSON.stringify(await finishEnrollment(state,args.base||DEFAULT_BASE,{wait:false}),null,2));}else if(command==='heartbeat'){const state=readState();if(!state)throw new Error('no_device_state');console.log(JSON.stringify(await heartbeat(state,args.base||DEFAULT_BASE),null,2));}else if(command==='daemon')await daemon(args);else if(command==='status')await status();else throw new Error(`unknown_command:${command}`);}catch(error){console.error(JSON.stringify({ok:false,error:error.message,status:error.status||null},null,2));process.exitCode=1;}
