import crypto from 'node:crypto';
import express from 'express';
import { callOperatorJson } from '../gateway/operator-proxy.mjs';
import { oauthSecret } from './oauth-secret.mjs';
import { PUBLIC_ORIGIN } from './config.mjs';

const COOKIE='__Host-light_remote_account';
const failures=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const digest=s=>crypto.createHash('sha256').update(String(s||'')).digest('hex');
const hmac=s=>crypto.createHmac('sha256',oauthSecret()).update(String(s)).digest('base64url');
const safeId=v=>/^[A-Za-z0-9._:-]{1,160}$/.test(String(v||''))?String(v):'';
function safeNext(value){const v=String(value||'/');return v.startsWith('/')&&!v.startsWith('//')&&!v.includes('\\')?v:'/';}
function cookies(req){const out={};for(const p of String(req.get('cookie')||'').split(';')){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim());}return out;}
function sessionToken(req){return String(cookies(req)[COOKIE]||'');}
function sessionHeader(token){return {'x-light-account-session':token};}
function setCookie(res,token,expiresAt){const max=Math.max(60,Math.min(7*86400,Math.floor((Number(expiresAt)-Date.now())/1000)));res.append('Set-Cookie',`${COOKIE}=${encodeURIComponent(token)}; Path=/; Max-Age=${max}; HttpOnly; Secure; SameSite=Strict; Priority=High`);}
function clearCookie(res){res.append('Set-Cookie',`${COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict; Priority=High`);}
function sameOrigin(req){const site=String(req.get('sec-fetch-site')||'').toLowerCase();if(site&&site!=='same-origin'&&site!=='none')return false;const origin=String(req.get('origin')||'');if(!origin)return true;try{return new URL(origin).origin===PUBLIC_ORIGIN;}catch{return false;}}
function csrf(token,purpose){return hmac(`${purpose}|${token}`);}
function validCsrf(token,purpose,value){const a=Buffer.from(csrf(token,purpose)),b=Buffer.from(String(value||''));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function page(title,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font:16px system-ui;background:#0b0f14;color:#e5e7eb;margin:0;min-height:100vh;display:grid;place-items:center}.card{width:min(620px,92vw);background:#111827;border:1px solid #334155;border-radius:14px;padding:24px;box-sizing:border-box}input,button,select{box-sizing:border-box;width:100%;padding:10px;margin:6px 0 14px;border:1px solid #475569;border-radius:8px;background:#0f172a;color:#fff}button{cursor:pointer;background:#2563eb}.muted{color:#94a3b8}.err{color:#fca5a5}.ok{color:#86efac}.caps label{display:block;margin:8px 0}.caps input{width:auto;margin:0 8px 0 0}code{background:#020617;padding:2px 5px;border-radius:5px}a{color:#93c5fd}.row{display:flex;gap:12px;align-items:center}.row form{margin-left:auto}.row form button{width:auto;margin:0}</style></head><body><main class="card">${body}</main></body></html>`;}
function loginHtml(next,msg=''){return page('Light Remote sign in',`<h1>Light Remote</h1><p class="muted">Sign in to approve a device enrollment.</p>${msg?`<p class="err">${esc(msg)}</p>`:''}<form method="post" action="/account/login"><input type="hidden" name="next" value="${esc(safeNext(next))}"><label>Email<input type="email" name="email" autocomplete="email" required autofocus></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button type="submit">Sign in</button></form><p class="muted">Credentials are used only to create the account session and are not exposed through MCP tools.</p>`);}
function approvalHtml({account,pending,token,msg=''}){const id=pending.enrollmentId,caps=(pending.requestedCapabilities||[]).map(c=>`<label><input type="checkbox" name="capability" value="${esc(c)}" checked> ${esc(c)}</label>`).join('');return page('Approve Light Remote device',`<div class="row"><div><h1>Approve device</h1><p class="muted">Signed in as ${esc(account.email||'account')}</p></div><form method="post" action="/account/logout"><input type="hidden" name="logoutCsrf" value="${esc(csrf(token,'logout'))}"><button type="submit">Sign out</button></form></div>${msg?`<p class="err">${esc(msg)}</p>`:''}<p>Device: <strong>${esc(pending.displayName)}</strong></p><p class="muted">${esc(pending.platform)} / ${esc(pending.architecture)} · Agent ${esc(pending.agentVersion)}</p><p class="muted">Fingerprint: <code>${esc(pending.fingerprintSummary)}</code></p><form method="post" action="/enroll/approve"><input type="hidden" name="enrollmentId" value="${esc(id)}"><input type="hidden" name="csrf" value="${esc(csrf(token,`enroll:${id}`))}"><label>One-time device code<input name="code" autocomplete="one-time-code" required placeholder="ABCD-EFGH"></label><label>Device name<input name="displayName" value="${esc(pending.displayName)}" maxlength="120" required></label><label>Policy profile<input name="policyProfile" value="${esc(pending.requestedPolicy||'default')}" maxlength="80" required></label><div class="caps"><strong>Approved capabilities</strong>${caps}</div><button type="submit">Approve this device</button></form><p class="muted">Only the capabilities requested by this device can be approved. Local device policy can still deny operations later.</p>`);}
async function identity(req){const token=sessionToken(req);if(!token)return null;try{const row=await callOperatorJson('GET','/v1/accounts/me',null,sessionHeader(token));return {token,account:row.account,session:row.session};}catch{return null;}}
async function pendingById(id){const row=await callOperatorJson('GET','/v1/enrollments');return (row.pending||[]).find(x=>x.enrollmentId===id)||null;}
function loginRate(req){const key=digest(req.ip||req.socket.remoteAddress||'unknown').slice(0,24),cut=Date.now()-10*60_000,rows=(failures.get(key)||[]).filter(t=>t>cut);failures.set(key,rows);return {key,rows,blocked:rows.length>=10};}
function rememberFailure(key,rows){rows.push(Date.now());failures.set(key,rows);}
function security(res){res.set('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");res.set('Cross-Origin-Opener-Policy','same-origin');}

export function registerHostedAccountRoutes(app){
  const form=express.urlencoded({extended:false,limit:'24kb'});
  app.get('/account/login',async(req,res)=>{security(res);const next=safeNext(req.query?.next);if(await identity(req))return res.redirect(303,next);return res.type('html').send(loginHtml(next));});
  app.post('/account/login',form,async(req,res)=>{security(res);if(!sameOrigin(req))return res.status(403).type('html').send(loginHtml('/', 'Cross-site sign-in request rejected.'));const next=safeNext(req.body?.next),rate=loginRate(req);if(rate.blocked){res.set('Retry-After','600');return res.status(429).type('html').send(loginHtml(next,'Too many failed sign-in attempts.'));}try{const row=await callOperatorJson('POST','/v1/accounts/login',{email:String(req.body?.email||''),password:String(req.body?.password||'')});failures.delete(rate.key);setCookie(res,row.token,row.session?.expiresAt);return res.redirect(303,next);}catch{rememberFailure(rate.key,rate.rows);return res.status(401).type('html').send(loginHtml(next,'Invalid email or password.'));}});
  app.post('/account/logout',form,async(req,res)=>{security(res);if(!sameOrigin(req))return res.sendStatus(403);const who=await identity(req);if(!who)return res.redirect(303,'/account/login');if(!validCsrf(who.token,'logout',req.body?.logoutCsrf))return res.sendStatus(403);try{await callOperatorJson('POST','/v1/accounts/logout',{},sessionHeader(who.token));}catch{}clearCookie(res);return res.redirect(303,'/');});
  app.get('/enroll',async(req,res)=>{security(res);const id=safeId(req.query?.id);if(!id)return res.status(400).type('html').send(page('Enrollment error','<h1>Invalid enrollment request</h1><p>The enrollment ID is missing or invalid.</p>'));const who=await identity(req);if(!who)return res.redirect(303,`/account/login?next=${encodeURIComponent(`/enroll?id=${id}`)}`);const pending=await pendingById(id);if(!pending)return res.status(404).type('html').send(page('Enrollment unavailable','<h1>Enrollment unavailable</h1><p>This request was not found, expired, or was already completed.</p>'));return res.type('html').send(approvalHtml({account:who.account,pending,token:who.token}));});
  app.post('/enroll/approve',form,async(req,res)=>{security(res);if(!sameOrigin(req))return res.sendStatus(403);const id=safeId(req.body?.enrollmentId),who=await identity(req);if(!who)return res.redirect(303,`/account/login?next=${encodeURIComponent(`/enroll?id=${id}`)}`);if(!id||!validCsrf(who.token,`enroll:${id}`,req.body?.csrf))return res.sendStatus(403);const pending=await pendingById(id);if(!pending)return res.status(404).type('html').send(page('Enrollment unavailable','<h1>Enrollment unavailable</h1><p>This request was not found, expired, or was already completed.</p>'));const requested=new Set(pending.requestedCapabilities||[]),raw=req.body?.capability,approved=[...new Set((Array.isArray(raw)?raw:raw?[raw]:[]).map(String).filter(x=>requested.has(x)))];if(!approved.length)return res.status(400).type('html').send(approvalHtml({account:who.account,pending,token:who.token,msg:'Select at least one requested capability.'}));try{const row=await callOperatorJson('POST','/v1/accounts/enrollments/approve',{code:String(req.body?.code||''),displayName:String(req.body?.displayName||pending.displayName).slice(0,120),policyProfile:String(req.body?.policyProfile||pending.requestedPolicy||'default').slice(0,80),approvedCapabilities:approved},sessionHeader(who.token));return res.type('html').send(page('Device approved',`<h1 class="ok">Device approved</h1><p><strong>${esc(row.device?.displayName||req.body?.displayName||pending.displayName)}</strong> can now finish enrollment and connect through the signed outbound device channel.</p><p class="muted">Device ID: <code>${esc(row.approval?.deviceId||row.device?.deviceId||'')}</code></p><p><a href="/">Return to Light Remote</a></p>`));}catch(error){return res.status(Number(error.status)||400).type('html').send(approvalHtml({account:who.account,pending,token:who.token,msg:error.message||'Enrollment approval failed.'}));}});
}

export function pruneHostedAccountState(){const cut=Date.now()-10*60_000;for(const [key,rows] of failures){const live=rows.filter(t=>t>cut);if(live.length)failures.set(key,live);else failures.delete(key);}}
