import crypto from 'node:crypto';
import express from 'express';
import { SignJWT, jwtVerify } from 'jose';
import { callOperatorJson } from '../gateway/operator-proxy.mjs';
import { MCP_RESOURCE, PUBLIC_ORIGIN } from './config.mjs';
import { oauthSecret } from './oauth-secret.mjs';

const ACCESS_TTL=3600, CODE_TTL=120, REFRESH_TTL=30*24*3600;
const ALLOWED_SCOPES=new Set(['remote:read','remote:write','remote:execute','remote:terminal','offline_access','openid','email']);
const authorizationCodes=new Map(), usedRefresh=new Map(), failures=new Map();
const now=()=>Math.floor(Date.now()/1000);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pkce=v=>crypto.createHash('sha256').update(String(v||'')).digest('base64url');

function parseScopes(value,{allowEmpty=false}={}){
  const raw=[...new Set(String(value||'').split(/\s+/).filter(Boolean))];
  if(!raw.length&&allowEmpty)return [];
  if(!raw.length||raw.some(v=>!ALLOWED_SCOPES.has(v))) throw new Error('invalid_scope');
  return raw;
}
function validRedirect(uri){try{const u=new URL(uri);return u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname));}catch{return false;}}
async function mint(type,claims,ttl,audience=MCP_RESOURCE){return new SignJWT({...claims,token_use:type}).setProtectedHeader({alg:'HS256',typ:'JWT'}).setIssuer(PUBLIC_ORIGIN).setAudience(audience).setIssuedAt().setExpirationTime(now()+ttl).setJti(crypto.randomUUID()).sign(oauthSecret());}
async function verify(token,type,audience=MCP_RESOURCE){const {payload}=await jwtVerify(String(token||''),oauthSecret(),{issuer:PUBLIC_ORIGIN,audience});if(payload.token_use!==type)throw new Error('invalid_token_use');return payload;}
async function mintClient(claims){return new SignJWT({...claims,token_use:'client'}).setProtectedHeader({alg:'HS256',typ:'JWT'}).setIssuer(PUBLIC_ORIGIN).setAudience(`${PUBLIC_ORIGIN}/oauth/register`).setIssuedAt().setJti(crypto.randomUUID()).sign(oauthSecret());}
async function clientFromId(id){try{const {payload:p}=await jwtVerify(String(id||''),oauthSecret(),{issuer:PUBLIC_ORIGIN,audience:`${PUBLIC_ORIGIN}/oauth/register`});return p.token_use==='client'&&Array.isArray(p.redirect_uris)?p:null;}catch{return null;}}
function requestKey(req){return crypto.createHash('sha256').update(String(req.ip||req.socket.remoteAddress||'unknown')).digest('hex').slice(0,24);}
function tooMany(req){const k=requestKey(req),cut=Date.now()-10*60*1000,rows=(failures.get(k)||[]).filter(t=>t>cut);failures.set(k,rows);return rows.length>=10;}
function recordFailure(req){const k=requestKey(req),rows=failures.get(k)||[];rows.push(Date.now());failures.set(k,rows);}
function issueAuthorizationCode(claims){const code=crypto.randomBytes(32).toString('base64url');authorizationCodes.set(code,{...claims,exp:now()+CODE_TTL});return code;}

export function oauthMetadata(){return {issuer:PUBLIC_ORIGIN,authorization_endpoint:`${PUBLIC_ORIGIN}/oauth/authorize`,token_endpoint:`${PUBLIC_ORIGIN}/oauth/token`,registration_endpoint:`${PUBLIC_ORIGIN}/oauth/register`,userinfo_endpoint:`${PUBLIC_ORIGIN}/userinfo`,scopes_supported:[...ALLOWED_SCOPES],response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],token_endpoint_auth_methods_supported:['none'],code_challenge_methods_supported:['S256'],authorization_response_iss_parameter_supported:true,client_id_metadata_document_supported:false};}
export function oidcMetadata(){return {...oauthMetadata(),subject_types_supported:['public'],claims_supported:['sub','email','email_verified']};}
export function protectedResourceMetadata(){return {resource:MCP_RESOURCE,authorization_servers:[PUBLIC_ORIGIN],scopes_supported:[...ALLOWED_SCOPES].filter(x=>x!=='offline_access'),resource_documentation:`${PUBLIC_ORIGIN}/support`};}
export function challengeValue(scopes,error='invalid_token',description='Authentication required'){return `Bearer resource_metadata="${PUBLIC_ORIGIN}/.well-known/oauth-protected-resource/mcp", scope="${scopes.join(' ')}", error="${error}", error_description="${String(description).replace(/["\\]/g,'')}"`;}
export function authErrorResult(scopes,error='invalid_token',description='Connect Light Remote to continue.'){return {content:[{type:'text',text:description}],_meta:{'mcp/www_authenticate':[challengeValue(scopes,error,description)]},isError:true};}
export async function authenticateAccess(req){const raw=String(req.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!raw)return {identity:null,error:'invalid_token'};try{const p=await verify(raw,'access');const scopes=parseScopes(p.scope);if(p.resource!==MCP_RESOURCE||!p.sub||!p.client_id)throw new Error('invalid_token');return {identity:{accountId:String(p.sub),clientId:String(p.client_id),scopes},error:null};}catch(e){return {identity:null,error:e.message==='invalid_scope'?'insufficient_scope':'invalid_token'};}}
export function requireScopes(identity,required){if(!identity)return authErrorResult(required);const have=new Set(identity.scopes||[]),missing=required.filter(s=>!have.has(s));return missing.length?authErrorResult(required,'insufficient_scope',`Additional permission required: ${missing.join(', ')}`):null;}

function authCsp(){return `default-src 'none'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'`; }
function authHtml(p,msg=''){
  const hidden=Object.entries(p).map(([k,v])=>`<input type="hidden" name="${esc(k)}" value="${esc(v)}">`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Light Remote authorization</title><style>body{font:16px system-ui;background:#090b0e;color:#e5e7eb;display:grid;place-items:center;min-height:100vh}.c{width:min(460px,92vw);padding:24px;border:1px solid #303844;border-radius:14px;background:#10141a}input,button{box-sizing:border-box;width:100%;padding:11px;margin:6px 0 14px;border-radius:8px;border:1px solid #303844;background:#0b0f14;color:#fff}button{background:#2563eb}.muted{color:#98a2b3}.err{color:#fca5a5}</style></head><body><main class="c"><h1>Light Remote</h1><p class="muted">Authorize ChatGPT to use your policy-bounded Light Remote devices.</p>${msg?`<p class="err">${esc(msg)}</p>`:''}<p class="muted">Requested permissions: ${esc(p.scope||'')}</p><form method="post" action="/oauth/authorize">${hidden}<label>Email<input type="email" name="email" autocomplete="email" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button type="submit">Authorize</button></form></main></body></html>`;
}
async function validateAuthorize(src){const clientId=String(src.client_id||''),client=await clientFromId(clientId),redirect=String(src.redirect_uri||''),resource=String(src.resource||'');if(!client||!client.redirect_uris.includes(redirect))throw new Error('invalid_client');if(String(src.response_type||'')!=='code')throw new Error('unsupported_response_type');if(resource!==MCP_RESOURCE)throw new Error('invalid_resource');const challenge=String(src.code_challenge||'');if(src.code_challenge_method!=='S256'||!/^[A-Za-z0-9_-]{43,128}$/.test(challenge))throw new Error('pkce_s256_required');return {clientId,redirect,resource,challenge,scope:parseScopes(src.scope).join(' '),state:String(src.state||'').slice(0,2048)};}

export function registerOAuth(app){
  const form=express.urlencoded({extended:false,limit:'24kb'}),json=express.json({limit:'32kb'});
  app.get('/.well-known/oauth-protected-resource',(_q,r)=>r.json(protectedResourceMetadata()));
  app.get('/.well-known/oauth-protected-resource/mcp',(_q,r)=>r.json(protectedResourceMetadata()));
  app.get('/.well-known/oauth-authorization-server',(_q,r)=>r.json(oauthMetadata()));
  app.get('/.well-known/openid-configuration',(_q,r)=>r.json(oidcMetadata()));
  app.post('/oauth/register',json,async(req,res)=>{try{const b=req.body||{},redirects=Array.isArray(b.redirect_uris)?[...new Set(b.redirect_uris.map(String))]:[];if(!redirects.length||redirects.length>10||redirects.some(x=>!validRedirect(x)))throw new Error('invalid_redirect_uris');if(b.token_endpoint_auth_method&&b.token_endpoint_auth_method!=='none')throw new Error('invalid_client_metadata');const grant_types=Array.isArray(b.grant_types)&&b.grant_types.length?b.grant_types.map(String):['authorization_code','refresh_token'],response_types=Array.isArray(b.response_types)&&b.response_types.length?b.response_types.map(String):['code'];if(grant_types.some(x=>!['authorization_code','refresh_token'].includes(x))||response_types.some(x=>x!=='code'))throw new Error('invalid_client_metadata');const client_name=String(b.client_name||'MCP client').slice(0,160),scope=b.scope?parseScopes(b.scope).join(' '):undefined;const client_id=await mintClient({redirect_uris:redirects,client_name,scope});return res.status(201).json({client_id,client_id_issued_at:now(),redirect_uris:redirects,client_name,grant_types,response_types,token_endpoint_auth_method:'none',...(scope?{scope}:{})});}catch(e){return res.status(400).json({error:e.message});}});
  app.get('/oauth/authorize',async(req,res)=>{try{const p=await validateAuthorize(req.query||{});res.set('Content-Security-Policy',authCsp(p.redirect));return res.type('html').send(authHtml({client_id:p.clientId,redirect_uri:p.redirect,response_type:'code',code_challenge:p.challenge,code_challenge_method:'S256',resource:p.resource,scope:p.scope,state:p.state}));}catch(e){return res.status(400).type('text').send(e.message);}});
  app.post('/oauth/authorize',form,async(req,res)=>{let p;try{p=await validateAuthorize(req.body||{});}catch(e){return res.status(400).type('text').send(e.message);}if(tooMany(req))return res.status(429).type('text').send('Too many failed authorization attempts.');try{const verified=await callOperatorJson('POST','/v1/plugin/auth/verify',{email:req.body.email,password:req.body.password});failures.delete(requestKey(req));const account=verified.account,code=issueAuthorizationCode({sub:account.accountId,email:account.email,client_id:p.clientId,redirect_uri:p.redirect,code_challenge:p.challenge,resource:MCP_RESOURCE,scope:p.scope});const out=new URL(p.redirect);out.searchParams.set('code',code);if(p.state)out.searchParams.set('state',p.state);out.searchParams.set('iss',PUBLIC_ORIGIN);return res.redirect(303,out.toString());}catch{recordFailure(req);res.set('Content-Security-Policy',authCsp(p.redirect));return res.status(401).type('html').send(authHtml({client_id:p.clientId,redirect_uri:p.redirect,response_type:'code',code_challenge:p.challenge,code_challenge_method:'S256',resource:p.resource,scope:p.scope,state:p.state},'Invalid email or password.'));}});
  app.get('/userinfo',async(req,res)=>{res.set('Cache-Control','no-store');const raw=String(req.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();try{const p=await verify(raw,'access'),scopes=new Set(parseScopes(p.scope));if(p.resource!==MCP_RESOURCE||!p.sub||!p.email)throw new Error('invalid_token');if(!scopes.has('openid')||!scopes.has('email'))return res.status(403).json({error:'insufficient_scope'});return res.json({sub:String(p.sub),email:String(p.email),email_verified:true});}catch{return res.status(401).set('WWW-Authenticate','Bearer error="invalid_token"').json({error:'invalid_token'});}});
  app.post('/oauth/token',form,async(req,res)=>{res.set('Cache-Control','no-store');res.set('Pragma','no-cache');const clientId=String(req.body.client_id||''),resource=String(req.body.resource||'');if(!await clientFromId(clientId))return res.status(401).json({error:'invalid_client'});if(resource!==MCP_RESOURCE)return res.status(400).json({error:'invalid_target'});try{if(req.body.grant_type==='authorization_code'){const codeKey=String(req.body.code||''),code=authorizationCodes.get(codeKey);if(!code||Number(code.exp)<=now()){authorizationCodes.delete(codeKey);throw new Error();}if(code.client_id!==clientId||code.redirect_uri!==String(req.body.redirect_uri||'')||code.resource!==resource||pkce(req.body.code_verifier)!==code.code_challenge)throw new Error();authorizationCodes.delete(codeKey);const common={sub:code.sub,email:code.email,client_id:clientId,resource,scope:code.scope};return res.json({access_token:await mint('access',common,ACCESS_TTL),token_type:'Bearer',expires_in:ACCESS_TTL,refresh_token:await mint('refresh',common,REFRESH_TTL),scope:code.scope,resource});}if(req.body.grant_type==='refresh_token'){const prior=await verify(req.body.refresh_token,'refresh');if(prior.client_id!==clientId||prior.resource!==resource||!prior.jti||usedRefresh.has(prior.jti))throw new Error();usedRefresh.set(prior.jti,Number(prior.exp));const common={sub:prior.sub,email:prior.email,client_id:clientId,resource,scope:prior.scope};return res.json({access_token:await mint('access',common,ACCESS_TTL),token_type:'Bearer',expires_in:ACCESS_TTL,refresh_token:await mint('refresh',common,REFRESH_TTL),scope:prior.scope,resource});}return res.status(400).json({error:'unsupported_grant_type'});}catch{return res.status(400).json({error:'invalid_grant'});}});
}
export function pruneOAuthState(){const t=now();for(const [code,row] of authorizationCodes)if(Number(row?.exp)<=t)authorizationCodes.delete(code);for(const [jti,exp] of usedRefresh)if(Number(exp)<=t)usedRefresh.delete(jti);}
