import crypto from 'node:crypto';
import { callOperatorJson } from '../gateway/operator-proxy.mjs';
import { sealOperatorPayload } from '../gateway/operator-crypto.mjs';
import { redactRestrictedText } from './response-sanitizer.mjs';

const opId=p=>`${p}-${crypto.randomUUID()}`;
const cleanDevice=d=>({deviceId:d.deviceId,name:d.displayName,platform:d.platform,architecture:d.architecture,state:d.state,capabilities:[...(d.effectiveCapabilities||d.capabilities||d.approvedCapabilities||[])]});
const cleanSession=s=>({sessionId:s.sessionId,deviceId:s.deviceId,state:s.state,workspace:s.workspace||'',gracePreset:s.gracePreset||null});
const cleanJob=j=>({jobId:j.jobId,state:j.state||null,running:!j.finishedAt,exitCode:j.exitCode??null});
const PRODUCT_CAPABILITIES=Object.freeze([
  'account-owned device enrollment with local-first A/B approval',
  'explicit device targeting with no silent fallback',
  'durable remote sessions and recoverable jobs/output',
  'bounded filesystem operations and native search',
  'managed non-PTY processes',
  'real PTY/ConPTY terminals with input, resize, signals, and persistent shells',
  'device-local final policy enforcement',
  'Main device and multi-device Fleet/Fleet Wall for entitled accounts',
  'signed outbound device channels and device identity',
  'device activity/live execution observability',
  'signed updates with an independent updater/helper and health-gated rollback'
]);

function stableAgentId(identity){return `plugin-${crypto.createHash('sha256').update(`${identity.accountId}|${identity.clientId}`).digest('hex').slice(0,40)}`;}
function safeAccount(a={}){return {plan:String(a.plan||'free'),mainDeviceId:a.mainDeviceId||null,fleet:a.fleetProvisioning?{deviceId:a.fleetProvisioning.deviceId||null,state:a.fleetProvisioning.state||null,reason:a.fleetProvisioning.reason||null,moduleVersion:a.fleetProvisioning.moduleVersion||null,agentVersion:a.fleetProvisioning.agentVersion||null,port:Number(a.fleetProvisioning.port)||null}:null};}
function safeRouting(r={}){return {mode:r.mode||null,state:r.state||null,draining:Boolean(r.draining),sessionCeiling:Number.isFinite(Number(r.sessionCeiling))?Number(r.sessionCeiling):null,queuedCommands:Number(r.queuedCommands)||0,inFlightCommands:Number(r.inFlightCommands)||0};}
function safeConnection(c={}){return {state:c.state||null,plan:c.plan||null,enforced:Boolean(c.enforced),reconnectGraceMs:Number.isFinite(Number(c.reconnectGraceMs))?Number(c.reconnectGraceMs):null};}
function safeUpdate(u={}){return {state:u.state||u.status||null,currentVersion:u.currentVersion||null,targetVersion:u.targetVersion||null,helperVersion:u.helperVersion||null,mode:u.mode||null,code:u.code||null};}
function safePolicy(d={}){const p=d.policy||{},mode=String(d.routing?.mode||'');return {profile:d.policyProfile||p.policyProfile||null,authority:mode==='local'?'local-main':'server-and-local',revision:Number(p.policyRevision)||null,approvedCapabilities:[...(p.approvedCapabilities||d.approvedCapabilities||d.capabilities||[])],effectiveCapabilities:[...(d.effectiveCapabilities||d.capabilities||[])],localFinalDeny:true};}
function cleanActivityEvent(e={}){const out={type:String(e.type||'activity'),status:e.status||null,route:e.route||null};if(e.requiredCapabilities)out.requiredCapabilities=[...e.requiredCapabilities];if(e.cwd)out.cwd=redactRestrictedText(String(e.cwd).slice(0,1024));if(e.note)out.note=redactRestrictedText(String(e.note).slice(0,1024));if(e.toolMeta&&typeof e.toolMeta==='object')out.tool={kind:e.toolMeta.kind||null,operation:e.toolMeta.op||null,label:e.toolMeta.label?redactRestrictedText(String(e.toolMeta.label).slice(0,512)):null};return out;}

export class AccountOperatorAdapter{
  constructor(identity){if(!identity?.accountId)throw new Error('plugin_identity_required');this.identity=identity;this.agentId=stableAgentId(identity);}
  async inventoryRaw(){return callOperatorJson('GET','/v1/devices');}
  async ownedDevicesRaw(){const row=await this.inventoryRaw();return (row.devices||[]).filter(d=>d.accountId===this.identity.accountId&&d.state!=='revoked');}
  async devices(){return (await this.ownedDevicesRaw()).map(cleanDevice);}
  async accountRaw(){const row=await callOperatorJson('GET',`/v1/admin/accounts/${encodeURIComponent(this.identity.accountId)}`);if(!row?.account)throw new Error('account_not_found');return row.account;}
  async deviceRaw(deviceId){const row=await callOperatorJson('GET',`/v1/devices/${encodeURIComponent(deviceId)}`),d=row.device;if(!d||d.accountId!==this.identity.accountId||d.state==='revoked')throw Object.assign(new Error('device_not_available'),{status:404});return d;}
  async connectionHelper(){const account=await this.accountRaw(),devices=await this.ownedDevicesRaw(),mainId=account.mainDeviceId||null;return {product:'Light Remote',purpose:'Governed remote computing for AI agents on explicitly authorized user-owned devices.',account:safeAccount(account),productCapabilities:[...PRODUCT_CAPABILITIES],onboarding:{normalFlow:['Install Light Remote on the device.','Open the device-local Local Wall and obtain the one-time A code.','Use the remote connection flow to exchange the A code and create the B/approval request.','Approve the request from the Local Wall.','Only then can the authorized account target the device.'],trustBoundary:'The remote MCP cannot mint its own A code or bypass Local Wall approval. This account may already contain enrolled devices so work can start after sign-in.'},topology:devices.map(d=>({deviceId:d.deviceId,name:d.displayName,role:d.deviceId===mainId?'main':'device',platform:d.platform,architecture:d.architecture,state:d.state,routing:safeRouting(d.routing||{}),effectiveCapabilities:[...(d.effectiveCapabilities||d.capabilities||[])]})),governance:{explicitTargetRequired:true,silentFallback:false,localPolicyFinalDeny:true,credentialsMustRemainLocal:true}};}
  async inspectDevice(deviceId){const [d,a]=await Promise.all([this.deviceRaw(deviceId),this.accountRaw()]);return {device:cleanDevice(d),role:a.mainDeviceId===d.deviceId?'main':'device',routing:safeRouting(d.routing||{}),connection:safeConnection(d.connection||{}),policy:safePolicy(d),update:safeUpdate(d.updateStatus||{}),fleet:{accountPlan:String(a.plan||'free'),mainDeviceId:a.mainDeviceId||null,provisioning:a.fleetProvisioning?{state:a.fleetProvisioning.state||null,deviceId:a.fleetProvisioning.deviceId||null,moduleVersion:a.fleetProvisioning.moduleVersion||null}:null}};}
  async recentActivity(deviceId,limit=50){await this.deviceRaw(deviceId);const n=Math.max(1,Math.min(Number(limit)||50,200)),row=await callOperatorJson('GET',`/v1/activity?deviceId=${encodeURIComponent(deviceId)}&limit=${n}`);return {deviceId,events:(row.events||[]).map(cleanActivityEvent)};}
  async setMainDevice(deviceId){await this.deviceRaw(deviceId);const row=await callOperatorJson('POST',`/v1/admin/accounts/${encodeURIComponent(this.identity.accountId)}/main-device`,{deviceId});return {account:safeAccount(row.account),mainDevice:cleanDevice(row.mainDevice)};}
  async revokeDevice(deviceId,reason='plugin_owner_revoked'){await this.deviceRaw(deviceId);const row=await callOperatorJson('POST',`/v1/devices/${encodeURIComponent(deviceId)}/revoke`,{accountId:this.identity.accountId,deviceId,reason:String(reason||'plugin_owner_revoked').slice(0,120)});return {deviceId:row.device?.deviceId||deviceId,state:row.device?.state||'revoked',revoked:true};}
  async removeDevice(deviceId,reason='plugin_owner_removed'){const d=await callOperatorJson('GET',`/v1/devices/${encodeURIComponent(deviceId)}`).then(x=>x.device);if(!d||d.accountId!==this.identity.accountId)throw Object.assign(new Error('device_not_available'),{status:404});const row=await callOperatorJson('POST',`/v1/plugin/accounts/${encodeURIComponent(this.identity.accountId)}/devices/${encodeURIComponent(deviceId)}/remove`,{reason:String(reason||'plugin_owner_removed').slice(0,120)});return {deviceId,removed:Boolean(row.removed?.removed||row.binding?.removed||row.removed===true)};}
  async openSession({deviceId,workspace='',gracePreset='60m'}={}){const d=await this.deviceRaw(deviceId);if(d.state!=='online')throw new Error('device_offline');const row=await callOperatorJson('POST','/v1/sessions/open',{accountId:this.identity.accountId,agentId:this.agentId,label:'ChatGPT Light Remote',workspace:String(workspace||'').slice(0,512),nodeId:d.nodeId,gracePreset});if(row?.session?.deviceId!==d.deviceId)throw new Error('session_target_mismatch');return cleanSession(row.session);}
  async sessionRaw(sessionId){const row=await callOperatorJson('GET',`/v1/sessions/${encodeURIComponent(sessionId)}?agentId=${encodeURIComponent(this.agentId)}`),s=row.session;if(!s)throw new Error('session_not_found');await this.deviceRaw(s.deviceId);return s;}
  async sessions(){const owned=new Set((await this.ownedDevicesRaw()).map(d=>d.deviceId)),row=await callOperatorJson('GET','/v1/sessions');return (row.sessions||[]).filter(s=>s.agentId===this.agentId&&owned.has(s.deviceId)).map(cleanSession);}
  async closeSession(sessionId){await this.sessionRaw(sessionId);const row=await callOperatorJson('POST',`/v1/sessions/${encodeURIComponent(sessionId)}/close`,{agentId:this.agentId});return cleanSession(row.session);}
  async fs(sessionId,fs,operationId=opId('fs'),waitMs=7000){const s=await this.sessionRaw(sessionId),payload={action:'fs',operationId,sessionId,agentId:this.agentId,nodeId:s.nodeId,fs,waitMs};return callOperatorJson('POST','/v1/fs',sealOperatorPayload(payload));}
  async search(sessionId,search,operationId=opId('search'),waitMs=7000){const s=await this.sessionRaw(sessionId),payload={action:'search',operationId,sessionId,agentId:this.agentId,nodeId:s.nodeId,search,waitMs};return callOperatorJson('POST','/v1/search',sealOperatorPayload(payload));}
  async process(sessionId,process,operationId=opId('process'),waitMs=7000){const s=await this.sessionRaw(sessionId),payload={action:'process',operationId,sessionId,agentId:this.agentId,nodeId:s.nodeId,process,waitMs};return callOperatorJson('POST','/v1/process',sealOperatorPayload(payload));}
  async terminal(sessionId,terminal,operationId=opId('terminal'),waitMs=7000){const s=await this.sessionRaw(sessionId),payload={action:'terminal',operationId,sessionId,agentId:this.agentId,nodeId:s.nodeId,terminal,waitMs};return callOperatorJson('POST','/v1/terminal',sealOperatorPayload(payload));}
  async exec(sessionId,script,{cwd='',operationId=opId('exec'),timeoutMs=600000,waitMs=7000}={}){const s=await this.sessionRaw(sessionId),payload={action:'exec_batch',operationId,sessionId,agentId:this.agentId,nodeId:s.nodeId,script:String(script),cwd:String(cwd||''),timeoutMs,waitMs,requiredCapabilities:[],note:'OpenAI Light Remote plugin'};return callOperatorJson('POST','/v1/execute',sealOperatorPayload(payload));}
  async job(jobId){const row=await callOperatorJson('GET',`/v1/jobs/${encodeURIComponent(jobId)}?agentId=${encodeURIComponent(this.agentId)}`),j=row.job;if(!j)throw new Error('job_not_found');await this.deviceRaw(j.deviceId);return cleanJob(j);}
  async output(jobId,stream='stdout',offset=0,limit=262144){await this.job(jobId);const q=new URLSearchParams({agentId:this.agentId,stream:stream==='stderr'?'stderr':'stdout',offset:String(Math.max(0,offset)),limit:String(Math.max(1,Math.min(limit,1048576)))});const row=await callOperatorJson('GET',`/v1/output/${encodeURIComponent(jobId)}?${q}`);return {jobId:row.jobId,stream:row.stream,offset:row.offset,returnedBytes:row.returnedBytes,totalBytes:row.totalBytes,hasMore:row.hasMore,output:redactRestrictedText(row.output)};}
}
