import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createOperatorCryptoFixture } from '../deploy/scripts/selftest-crypto-fixture.mjs';
import { deviceChannelMessage } from '../lib/device-proof.mjs';

const root=path.resolve(import.meta.dirname,'..');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'lr-plugin-hosted-'));
const socket=path.join(tmp,'operator.sock'),stateDir=path.join(tmp,'state'),logDir=path.join(tmp,'log');
fs.mkdirSync(stateDir,{recursive:true});fs.mkdirSync(logDir,{recursive:true});
const fixture=createOperatorCryptoFixture(stateDir),basePort=21000+(process.pid%1000)*2,origin=`http://127.0.0.1:${basePort}`;
const fixtureKeys=JSON.parse(fs.readFileSync(fixture.privateFile,'utf8')),fixturePrivate=crypto.createPrivateKey({key:Buffer.from(fixtureKeys.keys[fixture.kid],'base64'),format:'der',type:'pkcs8'}),fixturePublic=crypto.createPublicKey(fixturePrivate).export({format:'der',type:'spki'}).toString('base64');
process.env.OPERATOR_PUBLIC_KEYS_JSON=JSON.stringify({currentKid:fixture.kid,keys:{[fixture.kid]:fixturePublic}});
const secretFile=path.join(tmp,'oauth-secret');fs.writeFileSync(secretFile,crypto.randomBytes(48).toString('base64url'),{mode:0o600});
const accountId='acct_prod_test',email='prod-user@example.test',password=`Prod-${crypto.randomBytes(18).toString('base64url')}`;
const children=[];const cleanup=()=>{for(const child of children){try{if(child.exitCode==null)child.kill('SIGKILL');}catch{}}};process.once('exit',cleanup);const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function socketReq(method,target,body=null,headers={}){return new Promise((resolve,reject)=>{const payload=body==null?null:Buffer.from(JSON.stringify(body)),h={...headers};if(payload){h['content-type']='application/json';h['content-length']=payload.length;}const req=http.request({socketPath:socket,method,path:target,headers:h},res=>{let text='';res.on('data',c=>text+=c);res.on('end',()=>{let json;try{json=JSON.parse(text)}catch{json={raw:text}}resolve({status:res.statusCode,json});});});req.on('error',reject);if(payload)req.write(payload);req.end();});}
async function waitFile(file,logs){for(let i=0;i<120;i++){if(fs.existsSync(file))return;await sleep(40);}throw new Error(`wait_file_timeout:${file}\n${logs()}`);}
async function waitHttp(url,logs){for(let i=0;i<120;i++){try{const r=await fetch(url);if(r.ok)return;}catch{}await sleep(40);}throw new Error(`wait_http_timeout:${url}\n${logs()}`);}
function cookieFrom(res){const raw=res.headers.get('set-cookie')||'';const m=raw.match(/__Host-light_remote_account=([^;]+)/);return m?`__Host-light_remote_account=${m[1]}`:'';}
function hidden(html,name){const re=new RegExp(`name=["']${name}["'][^>]*value=["']([^"']+)["']`);return html.match(re)?.[1]||'';}
const operatorLogs=[];
const operator=spawn(process.execPath,[path.join(root,'operator-host/executor.mjs')],{cwd:root,env:{...process.env,OPERATOR_SOCKET:socket,OPERATOR_LOG_DIR:logDir,OPERATOR_STATE_DIR:stateDir,OPERATOR_KEY_FILE:fixture.privateFile,OPERATOR_ACCOUNT_ID:'reviewer',OPERATOR_ACCOUNT_PLAN:'free',OPERATOR_DEVICE_ID:'review-demo',OPERATOR_NODE_ID:'review-demo',OPERATOR_DEVICE_NAME:'Review Demo',OPERATOR_CONNECTION_LEASE_ENFORCE:'0',OPERATOR_ENROLLMENT_ACTIVATION_URL:`${origin}/enroll`,LIGHT_REMOTE_VERSION:'0.9.0-rc.26'},stdio:['ignore','pipe','pipe']});
children.push(operator);operator.stdout.on('data',d=>operatorLogs.push(String(d)));operator.stderr.on('data',d=>operatorLogs.push(String(d)));
await waitFile(socket,()=>operatorLogs.join(''));
let r=await socketReq('POST','/v1/admin/accounts/provision',{accountId,email,password,plan:'free'});assert.equal(r.status,201);assert.equal(r.json.account.accountId,accountId);
const pluginLogs=[];
const plugin=spawn(process.execPath,[path.join(root,'plugin-server/server.mjs')],{cwd:root,env:{...process.env,LIGHT_REMOTE_PLUGIN_ORIGIN:origin,LIGHT_REMOTE_PLUGIN_ALLOW_HTTP_LOOPBACK:'1',LIGHT_REMOTE_PLUGIN_HOST:'127.0.0.1',LIGHT_REMOTE_PLUGIN_PORT:String(basePort),LIGHT_REMOTE_PLUGIN_INTERNAL_HOST:'127.0.0.1',LIGHT_REMOTE_PLUGIN_INTERNAL_PORT:String(basePort+1),LIGHT_REMOTE_PLUGIN_INTERNAL_ALLOWED_IP:'127.0.0.1',LIGHT_REMOTE_PLUGIN_OAUTH_SECRET_FILE:secretFile,OPERATOR_SOCKET:socket,LIGHT_REMOTE_VERSION:'0.9.0-rc.26'},stdio:['ignore','pipe','pipe']});
children.push(plugin);plugin.stdout.on('data',d=>pluginLogs.push(String(d)));plugin.stderr.on('data',d=>pluginLogs.push(String(d)));
await waitHttp(`${origin}/healthz`,()=>pluginLogs.join(''));
let portalResp=await fetch(`${origin}/account`);assert.equal(portalResp.status,200);const portalHtml=await portalResp.text();assert.match(portalHtml,/Your devices/);assert.match(portalHtml,/official OpenAI Plugin/i);assert.doesNotMatch(portalHtml,/Vercel compatibility bridge/i);
for(const route of ['/login/','/usage/','/settings/','/assets/light-remote-portal.css']){const resp=await fetch(`${origin}${route}`);assert.equal(resp.status,200,route);}
let portalMe=await fetch(`${origin}/api/auth?action=me`);assert.equal(portalMe.status,401);
const portalLogin=await fetch(`${origin}/api/auth?action=login`,{method:'POST',headers:{'content-type':'application/json','origin':origin,'sec-fetch-site':'same-origin'},body:JSON.stringify({email,password})});assert.equal(portalLogin.status,200);const portalCookie=cookieFrom(portalLogin);assert.ok(portalCookie);
portalMe=await fetch(`${origin}/api/auth?action=me`,{headers:{cookie:portalCookie}});assert.equal(portalMe.status,200);assert.equal((await portalMe.json()).account.accountId,accountId);
const portalRoot=await fetch(origin,{headers:{cookie:portalCookie},redirect:'manual'});assert.equal(portalRoot.status,303);assert.equal(portalRoot.headers.get('location'),'/account');
const portalCrossSite=await fetch(`${origin}/api/auth?action=login`,{method:'POST',headers:{'content-type':'application/json','origin':'https://evil.example.test','sec-fetch-site':'cross-site'},body:JSON.stringify({email,password})});assert.equal(portalCrossSite.status,403);
console.log('plugin_full_account_portal=PASS');
const identity=crypto.generateKeyPairSync('ed25519');
const publicIdentityKey=identity.publicKey.export({format:'der',type:'spki'}).toString('base64');
const beginResp=await fetch(`${origin}/api/operator`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'enrollment-begin',payload:{publicIdentityKey,displayName:'Prod Test Device',platform:'linux',architecture:'x64',agentVersion:'0.9.0-rc.26',fingerprintSummary:'prod-test/linux/x64',capabilities:['filesystem','terminal'],policyProfile:'default'}})});
assert.equal(beginResp.status,200);const begun=await beginResp.json();const enrollment=begun.upstream.enrollment;assert.ok(enrollment.enrollmentId);assert.ok(enrollment.deviceCode);assert.equal(enrollment.activationUrl,`${origin}/enroll?id=${encodeURIComponent(enrollment.enrollmentId)}`);
let pageResp=await fetch(enrollment.activationUrl,{redirect:'manual'});assert.equal(pageResp.status,303);assert.match(pageResp.headers.get('location'),/^\/account\/login\?next=/);
const loginPage=await fetch(`${origin}${pageResp.headers.get('location')}`);assert.equal(loginPage.status,200);assert.match(await loginPage.text(),/Sign in to approve a device enrollment/);
const internalLogin=await socketReq('POST','/v1/accounts/login',{email,password});assert.equal(internalLogin.status,200);const cookie=`__Host-light_remote_account=${encodeURIComponent(internalLogin.json.token)}`;
pageResp=await fetch(enrollment.activationUrl,{headers:{cookie}});assert.equal(pageResp.status,200);const approvalPage=await pageResp.text();assert.match(approvalPage,/Prod Test Device/);const csrf=hidden(approvalPage,'csrf');assert.ok(csrf);
const approveBody=new URLSearchParams();
for(const [k,v] of [['enrollmentId',enrollment.enrollmentId],['csrf',csrf],['code',enrollment.deviceCode],['displayName','Prod Test Device'],['policyProfile','default'],['capability','filesystem'],['capability','terminal']])approveBody.append(k,v);
const approveResp=await fetch(`${origin}/enroll/approve`,{method:'POST',headers:{cookie,'content-type':'application/x-www-form-urlencoded','origin':origin,'sec-fetch-site':'same-origin'},body:approveBody});
assert.equal(approveResp.status,200);assert.match(await approveResp.text(),/Device approved/);
const pollResp=await fetch(`${origin}/api/operator`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'enrollment-poll',payload:{enrollmentId:enrollment.enrollmentId,pollToken:enrollment.pollToken}})});
assert.equal(pollResp.status,200);const polled=(await pollResp.json()).upstream.enrollment;assert.equal(polled.state,'approved');assert.equal(polled.accountId,accountId);assert.ok(polled.certificateSignature);
const deviceId=polled.deviceId,nodeId=deviceId;
const sign=(action,payload)=>{const timestamp=Date.now(),nonce=crypto.randomBytes(18).toString('base64url'),signature=crypto.sign(null,Buffer.from(deviceChannelMessage({deviceId,action,timestamp,nonce,payload})),identity.privateKey).toString('base64url');return {deviceId,timestamp,nonce,signature,payload};};
const connectPayload={nodeId,agentVersion:'0.9.0-rc.26',requestedLeaseMs:60*60*1000,reconnectGraceMs:30*60*1000};
const connectResp=await fetch(`${origin}/device-channel/connect`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sign('connect',connectPayload))});
const connected=await connectResp.json();if(connectResp.status!==200)console.log('CONNECT_DEBUG',connectResp.status,connected);assert.equal(connectResp.status,200);assert.equal(connected.connection.state,'connected');
const crossSite=await fetch(`${origin}/account/login`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','origin':'https://evil.example.test','sec-fetch-site':'cross-site'},body:new URLSearchParams({next:'/'})});assert.equal(crossSite.status,403);
process.env.OPERATOR_SOCKET=socket;
const { AccountOperatorAdapter }=await import(`./operator-adapter.mjs?hosted=${Date.now()}`);
const adapter=new AccountOperatorAdapter({accountId,clientId:'hosted-selftest-client',scopes:['remote:read']});
const visible=await adapter.devices();assert.equal(visible.length,1);assert.equal(visible[0].deviceId,deviceId);assert.equal(visible[0].name,'Prod Test Device');assert.ok(!visible.some(x=>x.deviceId==='review-demo'));
await assert.rejects(()=>adapter.openSession({deviceId:'review-demo'}),/device_not_available/);
const hello={nodeId,agentVersion:'0.9.0-rc.26',sessionCeiling:2,draining:false,capabilities:['filesystem','terminal'],policyRevision:1,waitMs:0};
let channelResp=await fetch(`${origin}/device-channel/poll`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sign('poll',hello))});
assert.equal(channelResp.status,200);assert.equal((await channelResp.json()).channel.node.state,'online');
const session=await adapter.openSession({deviceId,workspace:'/tmp',gracePreset:'30m'});assert.equal(session.deviceId,deviceId);assert.equal(session.workspace,'/tmp');
const waitHello={...hello,waitMs:7000};
const dispatchPromise=fetch(`${origin}/device-channel/poll`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sign('poll',waitHello))});
await sleep(60);
const execPromise=adapter.exec(session.sessionId,"printf 'hosted-account-job-ok\n'",{cwd:'/tmp',operationId:'hosted-account-job-00000001',timeoutMs:10000,waitMs:7000});
const dispatchResp=await dispatchPromise;assert.equal(dispatchResp.status,200);const dispatched=await dispatchResp.json();assert.equal(dispatched.channel.state,'command');
const command=dispatched.channel.command;assert.equal(command.accountId,accountId);assert.equal(command.deviceId,deviceId);assert.equal(command.payload.script,"printf 'hosted-account-job-ok\n'");
const resultPayload={commandId:command.commandId,status:'ok',exitCode:0,stdout:'hosted-account-job-ok\n',stderr:'',durationMs:4};
const resultResp=await fetch(`${origin}/device-channel/result`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sign('result',resultPayload))});assert.equal(resultResp.status,200);assert.equal((await resultResp.json()).accepted,true);
const executed=await execPromise;assert.equal(executed.job.status,'ok');assert.equal(executed.job.accountId,accountId);assert.equal(executed.job.deviceId,deviceId);
const output=await adapter.output(executed.job.jobId);assert.equal(output.output,'hosted-account-job-ok\n');
const denyPollPromise=fetch(`${origin}/device-channel/poll`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sign('poll',waitHello))});
await sleep(60);
const denyExecPromise=adapter.exec(session.sessionId,'sudo systemctl restart ssh',{cwd:'/tmp',operationId:'hosted-policy-deny-00000001',timeoutMs:10000,waitMs:7000});
const denyDispatchResp=await denyPollPromise;assert.equal(denyDispatchResp.status,200);const denyDispatch=await denyDispatchResp.json();const denyCommand=denyDispatch.channel.command;
const denyResult={commandId:denyCommand.commandId,status:'error',exitCode:126,stdout:'',stderr:'local capability denied: sudo-on-demand,systemctl\n',durationMs:2};
const denyResultResp=await fetch(`${origin}/device-channel/result`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(sign('result',denyResult))});assert.equal(denyResultResp.status,200);assert.equal((await denyResultResp.json()).accepted,true);
const deniedExec=await denyExecPromise;assert.equal(deniedExec.job.exitCode,126);assert.equal(deniedExec.job.status,'error');
const closed=await adapter.closeSession(session.sessionId);assert.equal(closed.state,'closed');
const vip=await socketReq('POST',`/v1/admin/accounts/${accountId}/entitlement`,{plan:'vip',sourceRef:'openai-review-selftest'});assert.equal(vip.status,200);assert.equal(vip.json.account.plan,'vip');assert.equal(vip.json.entitlements.fleetWall,true);
const helper=await adapter.connectionHelper();assert.equal(helper.account.plan,'vip');assert.equal(helper.topology.length,1);assert.equal(helper.topology[0].deviceId,deviceId);assert.equal(helper.governance.silentFallback,false);assert.match(helper.onboarding.trustBoundary,/cannot mint its own A code/i);
const inspected=await adapter.inspectDevice(deviceId);assert.equal(inspected.device.deviceId,deviceId);assert.equal(inspected.policy.localFinalDeny,true);assert.equal(inspected.fleet.accountPlan,'vip');
const activity=await adapter.recentActivity(deviceId,50);assert.equal(activity.deviceId,deviceId);assert.ok(activity.events.length>0);const deniedEvent=activity.events.find(event=>event.status==='denied'&&event.exitCode===126);assert.ok(deniedEvent);assert.equal(deniedEvent.note,'Denied by local device policy.');for(const event of activity.events){assert.equal(event.accountId,undefined);assert.equal(event.jobId,undefined);assert.equal(event.sessionId,undefined);assert.equal(event.agentId,undefined);assert.equal(event.requestId,undefined);assert.equal(event.script,undefined);assert.equal(event.chunk,undefined);}
const main=await adapter.setMainDevice(deviceId);assert.equal(main.account.mainDeviceId,deviceId);assert.equal(main.mainDevice.deviceId,deviceId);
const revoked=await adapter.revokeDevice(deviceId,'openai_review_selftest');assert.equal(revoked.revoked,true);assert.equal(revoked.state,'revoked');
const afterRevoke=await adapter.devices();assert.equal(afterRevoke.length,0);
const removed=await adapter.removeDevice(deviceId,'openai_review_selftest_cleanup');assert.equal(removed.removed,true);
const missing=await socketReq('GET',`/v1/devices/${deviceId}`);assert.equal(missing.status,404);
const accountAfter=await socketReq('GET',`/v1/admin/accounts/${accountId}`);assert.equal(accountAfter.status,200);assert.equal(accountAfter.json.account.mainDeviceId,null);
const rotatedPassword=await socketReq('POST',`/v1/admin/accounts/${accountId}/password/rotate`,{});assert.equal(rotatedPassword.status,200);assert.equal(rotatedPassword.json.verified,true);assert.ok(rotatedPassword.json.temporaryPassword.length>=16);assert.ok(rotatedPassword.json.invalidatedSessions>=1);
const staleSession=await socketReq('GET','/v1/accounts/me',null,{'x-light-account-session':internalLogin.json.token});assert.equal(staleSession.status,401);
const rotatedLogin=await socketReq('POST','/v1/accounts/login',{email,password:rotatedPassword.json.temporaryPassword});assert.equal(rotatedLogin.status,200);assert.equal(rotatedLogin.json.account.accountId,accountId);
console.log('plugin_local_admin_password_rotation=PASS');
console.log('plugin_hosted_product_lifecycle=PASS');
console.log('plugin_hosted_account_session_job_output=PASS');
console.log('plugin_hosted_account_enrollment_channel_isolation=PASS');
plugin.kill('SIGTERM');operator.kill('SIGTERM');
await Promise.all(children.map(child=>new Promise(resolve=>child.once('exit',resolve))));
fs.rmSync(tmp,{recursive:true,force:true});process.removeListener('exit',cleanup);
console.log('plugin_hosted_selftest=PASS');
