import { z } from 'zod';
import { AccountOperatorAdapter } from './operator-adapter.mjs';
import { requireScopes } from './oauth.mjs';
import { redactRestrictedText, sanitizeForMcp } from './response-sanitizer.mjs';

const id=z.string().regex(/^[A-Za-z0-9._:-]{1,160}$/);
const opId=z.string().regex(/^[A-Za-z0-9._:-]{8,160}$/).optional();
const pathText=z.string().min(1).max(4096);
const security=scopes=>[{type:'oauth2',scopes}];
export const PLUGIN_TOOL_SECURITY = Object.create(null);
function register(server,name,config,cb){
  PLUGIN_TOOL_SECURITY[name]=Array.isArray(config.securitySchemes)?config.securitySchemes.map(x=>({...x,scopes:[...(x.scopes||[])]})):[];
  return server.registerTool(name,config,cb);
}
const ann=(readOnly,destructive,openWorld,idempotent=false)=>({readOnlyHint:readOnly,destructiveHint:destructive,openWorldHint:openWorld,idempotentHint:idempotent});
const asResult=value=>{const safe=sanitizeForMcp(value),structured=Array.isArray(safe)?{items:safe}:safe&&typeof safe==='object'?safe:{value:safe};return {content:[{type:'text',text:JSON.stringify(safe,null,2)}],structuredContent:structured};};
const opView=row=>({ok:Boolean(row?.ok),data:row?.data??null,job:row?.job?{jobId:row.job.jobId,state:row.job.state||null,running:!row.job.finishedAt,exitCode:row.job.exitCode??null}:null});

function handler(identity,scopes,fn){return async args=>{const auth=requireScopes(identity,scopes);if(auth)return auth;try{return asResult(await fn(new AccountOperatorAdapter(identity),args||{}));}catch(error){return {content:[{type:'text',text:redactRestrictedText(error?.message||'Light Remote operation failed.')}],isError:true};}};}

export function registerPluginTools(server,identity){
  register(server,'light_remote_list_devices',{title:'List Light Remote devices',description:'List the current account’s enrolled Light Remote devices and policy-bounded capabilities before choosing a target.',securitySchemes:security(['remote:read']),annotations:ann(true,false,false,true)},handler(identity,['remote:read'],(a)=>a.devices()));

  register(server,'light_remote_open_session',{title:'Open a remote session',description:'Open or reuse a durable session on one explicit Light Remote device. Use before file, command, process, or terminal work.',inputSchema:{deviceId:id,workspace:z.string().max(512).optional(),gracePreset:z.enum(['15m','30m','45m','60m']).optional()},securitySchemes:security(['remote:write']),annotations:ann(false,false,false,true)},handler(identity,['remote:write'],(a,x)=>a.openSession(x)));

  register(server,'light_remote_list_sessions',{title:'List remote sessions',description:'List durable sessions owned by this ChatGPT connection for recovery after an interrupted chat or transport.',securitySchemes:security(['remote:read']),annotations:ann(true,false,false,true)},handler(identity,['remote:read'],a=>a.sessions()));

  register(server,'light_remote_close_session',{title:'Close a remote session',description:'Close one durable Light Remote session when the task is finished. Running jobs are not silently re-run or moved.',inputSchema:{sessionId:id},securitySchemes:security(['remote:write']),annotations:ann(false,false,false,true)},handler(identity,['remote:write'],(a,x)=>a.closeSession(x.sessionId)));

  register(server,'light_remote_list_files',{title:'List remote files',description:'List a directory on the selected session target. This does not modify filesystem content.',inputSchema:{sessionId:id,path:pathText,maxEntries:z.number().int().min(1).max(1000).optional(),maxDepth:z.number().int().min(0).max(3).optional()},securitySchemes:security(['remote:read']),annotations:ann(true,false,false,true)},handler(identity,['remote:read'],async(a,x)=>opView(await a.fs(x.sessionId,{op:'list',path:x.path,maxEntries:x.maxEntries,maxDepth:x.maxDepth||0}))));

  register(server,'light_remote_read_file',{title:'Read a remote text file',description:'Read a bounded text range from a file on the selected session target.',inputSchema:{sessionId:id,path:pathText,startLine:z.number().int().min(1).optional(),maxLines:z.number().int().min(1).max(5000).optional(),tailLines:z.number().int().min(1).max(5000).optional()},securitySchemes:security(['remote:read']),annotations:ann(true,false,false,true)},handler(identity,['remote:read'],async(a,x)=>opView(await a.fs(x.sessionId,{op:'read',path:x.path,startLine:x.startLine,maxLines:x.maxLines,tailLines:x.tailLines}))));

  register(server,'light_remote_search_files',{title:'Search remote files',description:'Start or read a bounded native file-name/content search on the selected target. Starting a search creates a managed search handle but does not alter user files.',inputSchema:{sessionId:id,operation:z.enum(['start','results','cancel']),operationId:opId,path:pathText.optional(),searchId:z.string().max(160).optional(),searchType:z.enum(['content','files']).optional(),pattern:z.string().max(4096).optional(),literalSearch:z.boolean().optional(),ignoreCase:z.boolean().optional(),filePattern:z.string().max(1024).optional(),offset:z.number().int().min(0).optional(),limit:z.number().int().min(1).max(500).optional()},securitySchemes:security(['remote:read']),annotations:ann(false,false,false,false)},handler(identity,['remote:read'],async(a,x)=>{const search=x.operation==='start'?{op:'start',path:x.path,searchType:x.searchType||'content',pattern:x.pattern,literalSearch:Boolean(x.literalSearch),ignoreCase:x.ignoreCase!==false,filePattern:x.filePattern||'',maxResults:500}:x.operation==='results'?{op:'results',searchId:x.searchId,offset:x.offset||0,limit:x.limit||100}:{op:'cancel',searchId:x.searchId};return opView(await a.search(x.sessionId,search,x.operationId));}));

  register(server,'light_remote_write_file',{title:'Write a remote text file',description:'Rewrite or append text on the selected target. Rewriting can replace existing content, so use only when the user intends a file change.',inputSchema:{sessionId:id,operationId:opId,path:pathText,content:z.string().max(8000000),mode:z.enum(['rewrite','append']).optional(),createParents:z.boolean().optional()},securitySchemes:security(['remote:write']),annotations:ann(false,true,false,false)},handler(identity,['remote:write'],async(a,x)=>opView(await a.fs(x.sessionId,{op:'write',path:x.path,content:x.content,mode:x.mode||'rewrite',atomic:true,createParents:Boolean(x.createParents)},x.operationId))));

  register(server,'light_remote_edit_file',{title:'Edit an exact remote text block',description:'Replace an exact text block in a remote file. The operation fails when the expected replacement count does not match.',inputSchema:{sessionId:id,operationId:opId,path:pathText,oldText:z.string().min(1).max(4000000),newText:z.string().max(4000000),expectedReplacements:z.number().int().min(1).max(100).optional()},securitySchemes:security(['remote:write']),annotations:ann(false,true,false,false)},handler(identity,['remote:write'],async(a,x)=>opView(await a.fs(x.sessionId,{op:'edit',path:x.path,oldText:x.oldText,newText:x.newText,expectedReplacements:x.expectedReplacements||1},x.operationId))));

  register(server,'light_remote_exec',{title:'Execute a remote command',description:'Run a bounded shell, PowerShell, or platform command inside an explicit durable session. Commands may modify files, services, repositories, or external systems; device policy remains authoritative.',inputSchema:{sessionId:id,operationId:opId,script:z.string().min(1).max(1000000),cwd:pathText.optional(),timeoutMs:z.number().int().min(1000).max(7200000).optional(),waitMs:z.number().int().min(0).max(7000).optional()},securitySchemes:security(['remote:execute']),annotations:ann(false,true,true,false)},handler(identity,['remote:execute'],async(a,x)=>opView(await a.exec(x.sessionId,x.script,{cwd:x.cwd,operationId:x.operationId,timeoutMs:x.timeoutMs,waitMs:x.waitMs}))));

  register(server,'light_remote_process',{title:'Control a managed remote process',description:'Start, inspect, send input to, or stop a durable non-PTY process. Starting or controlling a process can have filesystem or network side effects.',inputSchema:{sessionId:id,operation:z.enum(['start','input','output','list','stop']),operationId:opId,processId:z.string().max(160).optional(),script:z.string().max(1000000).optional(),cwd:pathText.optional(),data:z.string().max(1048576).optional(),eof:z.boolean().optional(),stream:z.enum(['stdout','stderr']).optional(),offset:z.number().int().min(0).optional(),limit:z.number().int().min(1).max(1048576).optional(),force:z.boolean().optional(),timeoutMs:z.number().int().min(0).max(86400000).optional()},securitySchemes:security(['remote:execute']),annotations:ann(false,true,true,false)},handler(identity,['remote:execute'],async(a,x)=>{const p=x.operation==='start'?{op:'start',script:x.script,cwd:x.cwd,timeoutMs:x.timeoutMs}:x.operation==='input'?{op:'input',processId:x.processId,data:x.data||'',eof:Boolean(x.eof)}:x.operation==='output'?{op:'output',processId:x.processId,stream:x.stream||'stdout',offset:x.offset||0,limit:x.limit||262144}:x.operation==='list'?{op:'list'}:{op:'stop',processId:x.processId,force:Boolean(x.force)};return opView(await a.process(x.sessionId,p,x.operationId));}));

  register(server,'light_remote_terminal',{title:'Control a remote PTY or ConPTY terminal',description:'Start or interact with a real PTY/ConPTY terminal for interactive tools, Ctrl-C, resize, and persistent shells. Terminal input can cause irreversible local or external side effects.',inputSchema:{sessionId:id,operation:z.enum(['start','input','output','resize','signal','list','stop']),operationId:opId,terminalId:z.string().max(160).optional(),shell:z.string().max(80).optional(),cwd:pathText.optional(),data:z.string().max(1048576).optional(),offset:z.number().int().min(0).optional(),limit:z.number().int().min(1).max(1048576).optional(),cols:z.number().int().min(20).max(400).optional(),rows:z.number().int().min(5).max(200).optional(),signal:z.enum(['interrupt','terminate','kill']).optional(),force:z.boolean().optional()},securitySchemes:security(['remote:terminal']),annotations:ann(false,true,true,false)},handler(identity,['remote:terminal'],async(a,x)=>{const t={op:x.operation};for(const k of ['terminalId','shell','cwd','data','offset','limit','cols','rows','signal','force'])if(x[k]!==undefined)t[k]=x[k];return opView(await a.terminal(x.sessionId,t,x.operationId));}));

  register(server,'light_remote_job',{title:'Read a remote job',description:'Read durable job status after a remote operation without repeating the action.',inputSchema:{jobId:id},securitySchemes:security(['remote:read']),annotations:ann(true,false,false,true)},handler(identity,['remote:read'],(a,x)=>a.job(x.jobId)));
  register(server,'light_remote_output',{title:'Read remote job output',description:'Read bounded stdout or stderr from a durable job by byte offset.',inputSchema:{jobId:id,stream:z.enum(['stdout','stderr']).optional(),offset:z.number().int().min(0).optional(),limit:z.number().int().min(1).max(1048576).optional()},securitySchemes:security(['remote:read']),annotations:ann(true,false,false,true)},handler(identity,['remote:read'],(a,x)=>a.output(x.jobId,x.stream,x.offset,x.limit)));
}
