module.exports = function handler(req, res) {
  res.setHeader('Cache-Control','no-store'); res.setHeader('X-Robots-Tag','noindex,nofollow,noarchive');
  if(req.method!=='GET') return res.status(405).json({ok:false,error:'method_not_allowed'});
  return res.status(200).json({ok:true,project:'light-remote-mcp',version:'0.9.0-beta.1',purpose:'Light Remote MCP relay to the owner ARM operator hub',
    activePath:'ChatGPT -> Vercel bridge -> ARM hub -> selected node executor',upstream:'https://mcp.dashboard.thaiduy.store',wall:'https://wall.dashboard.thaiduy.store',
    recoveryDocs:['CURRENT_STATE.md','AI_BRIDGE_GUIDE.md','SESSION_OWNERSHIP_V0_5.md','HUB_TOPOLOGY_V0_5.md','PRODUCT_PLATFORM_PLAN_V0_6_TO_PUBLIC_PLUGIN.md','DEVICE_PRESENCE_V0_6.md','DEVICE_ENROLLMENT_V0_7.md','FLEET_ROUTING_V0_8.md','PLATFORM_ADAPTERS_V0_9.md','PORTABILITY.md'],
    auth:{plusCurrent:'ChatGPT Plus uses @Vercel GET plus device-grant authorization. Bootstrap devices, choose one connected device, request access, approve on that device Local Wall, then poll for a device-scoped capability; no custom MCP and no x-bridge-session header from ChatGPT',legacyOwner:'POST /api/auth + x-bridge-session remains for non-Plus/reference operator clients',staticSharedBearer:false,directMcp:'Business/Enterprise/Edu test/future Plugin lane only'},
    plusBridge:{requiredForCurrentOwner:true,edge:'GET /api/operator?via=plus on the Vercel deployment',bootstrap:'action=devices-bootstrap before authorization; select one explicit connected deviceId',authorizationBegin:'action=authorize-begin&p=<base64url {agentId,label,deviceId}>',authorizationPoll:'action=authorize-poll&p=<base64url {requestId,pollToken}>',ownerApproval:'open the selected device Wall at /approve, enter the short code, then Approve or Deny; no duration or Connect step',approvalPath:'/approve; the actual device Wall origin is deployment-specific (localhost/private VPN/reverse proxy)',session:'ps capability scoped to grantId + deviceId + connectionId and bounded by the finite Device Connection Lease; no fixed one-hour human approval lifetime',reuse:'additional ChatGPT windows requesting the same device while its grant is active receive a new ps for the same grant without owner re-approval',grantEndsOn:['15-60 minute grant idle grace after all Agent lanes/activity stop','device disconnect','hard device lease expiry','device revoke','connection identity change'],upstreamGate:'production-or-preview scoped Vercel OIDC plus ARM-verified device access grant',payload:'base64url JSON in ?p= for session-open/exec',actions:['devices-bootstrap','authorize-begin','authorize-poll','capabilities','devices','fleet','device','device-connection','sessions','session-open','session-resume','session-hold','session-close','session','exec','job','output'],rule:'all mutable operations require stable semantic IDs; owner passwords and long-lived credentials never enter the URL'},
    deviceEnrollment:{agentLogin:'node device-agent/operator-agent.mjs login',codeTtlMinutes:10,codeInActivationUrl:false,pollTokenBits:256,keyAlgorithm:'Ed25519',approvedDeviceStarts:'offline',onlineRequiresSignedHeartbeat:true,localFinalDenyBoundary:true,linuxDaemon:'device-agent/install-linux-service.sh',windowsDevPersistence:'per-user Scheduled Task / Interactive / Limited',remoteLeafExecution:'live-v0.8',outboundChannel:'leaf -> ARM Hub /device-channel/{poll,result}',channelAuth:'Ed25519 signed timestamp+nonce+payload hash'},
    sessionStart:{agentId:'generate one stable random agent id for each ChatGPT chat/window, e.g. a_<uuid>',openId:'stable id for one open attempt',plusOpen:'GET /api/operator?via=plus&ps=<device-grant-capability>&action=session-open&p=<base64url-json>',legacyOpen:'POST /api/operator body={action:"session-open",payload:{...}}',targetRule:'the ps grant already fixes one device; session-open must target that device/node and cross-device target mutation is rejected'},
    operatorEndpoints:{plusPrefix:'GET /api/operator?via=plus&action=',capabilities:'capabilities',devices:'devices',device:'device',enrollmentBegin:'POST action=enrollment-begin payload={publicIdentityKey,displayName,platform,architecture,agentVersion,fingerprintSummary,capabilities,policyProfile}',enrollmentPoll:'POST action=enrollment-poll payload={enrollmentId,pollToken}',enrollments:'action=enrollments',enrollmentCancel:'POST action=enrollment-cancel payload={enrollmentId}',enrollmentApprove:'POST action=enrollment-approve payload={code,displayName,approvedCapabilities,policyProfile}',deviceHeartbeat:'POST action=device-heartbeat payload={deviceId,timestamp,nonce,capabilities,signature}',deviceRevoke:'POST action=device-revoke payload={deviceId,reason}',devicePolicy:'POST action=device-policy payload={deviceId,policyProfile,approvedCapabilities}',fleet:'action=fleet',nodeDrain:'POST action=node-drain payload={nodeId,draining}',sessionResume:'session-resume',sessionClose:'session-close',session:'session',sessions:'sessions',sessionStats:'session-stats',exec:'POST action=exec payload={operationId,script,cwd,timeoutMs,waitMs,sessionId,agentId,nodeId?,requiredCapabilities?,note}',job:'job',output:'output'},
    readRule:'Current ChatGPT Plus calls enter through @Vercel and /api/operator?via=plus. Bootstrap inventory first, then request one explicit device. If no active Device Access Grant exists, the selected device Local Wall receives a pending request; one device approval unlocks multiple ChatGPT Agent sessions until that finite Device Connection Lease closes. Vercel OIDC remains mandatory upstream, legacy owner APIs may still require x-bridge-session, and enrolled leaf traffic remains Ed25519-authenticated and outbound-only.',
    sessionPolicy:{laneKey:'(deviceId, agentId)',ownerMismatch:'409 session_owner_mismatch',defaultReconnectGraceMinutes:30,reconnectGraceMinutes:[15,30,45,60],unlimited:false,activeJobHold:true,maxActiveSessions:5,perNodeCeiling:'advertised by each leaf; ARM local ceiling remains 5',targetBinding:'each Agent lane is bound to one deviceId/nodeId; the same agentId may own a separate lane on another device',deviceConnectionLease:{freeMaxHours:4,proMaxHours:24,vipMaxHours:72,hardExpiry:true,autoRenewFromToolActivity:false},sessionHistoryDays:7,currentJobTimeoutHours:2},
    platformAdapters:{linux:{status:'v0.9 live accepted on AMD x64',privilegePolicy:'sudo-on-demand is owner-profile controlled; systemd permits the grantable sudo path while signed policy + device-local deny decide effective use'},windows:{status:'v0.9 live accepted',shell:'Windows PowerShell',devPersistence:'per-user Scheduled Task; online while enrolled user is signed in',serviceMode:'optional for password-backed accounts',capabilityInference:'device-side final check before spawn'},macos:{status:'deferred'}},
    deviceModel:{presenceIndependentFromSessions:true,livePolicy:{ownerManaged:true,signedRevision:true,webPath:'/device-policy?id=<deviceId>',sudoToggle:'sudo-on-demand'},currentDevice:'arm-local',currentNode:'arm',presenceTtlSeconds:90,heartbeatSeconds:30,persistentRegistry:true,enrollment:'v0.7 accepted foundation',remoteRouting:'v0.8 live',routing:{hubNode:'arm',leafMode:'outbound-only',explicitTarget:true,silentFallback:false,drain:true,commandLeaseMs:12000,channelTtlMs:20000}},
    rules:['One (deviceId, agentId) pair owns at most one live operator session lane; one device grant may contain many Agent lanes.','Device approval never implies online; signed key proof is required.','Approved capabilities cannot exceed device-requested/grantable capabilities; owner policy may toggle them after enrollment and device-local explicit deny may still reduce them.','Owner device-policy revisions are signed and synchronized through the outbound channel before execution.','Each platform adapter re-infers required capabilities from the script before spawn; caller metadata alone is never sufficient.','Leaf sessions/jobs are explicitly target-bound; an offline or draining target fails closed and never silently runs on ARM.','Device private keys remain local; device code is one-time and not stored plaintext.','No static shared Bearer secret is used.','Use Git/worktree discipline for repo concurrency.','Never put passwords, private keys, cookies, device codes, or long-lived credentials in URL payloads; the GET-only Plus compatibility lane may carry only its one-time poll token and device-grant-scoped ps capability.','Structured POST is required for legacy payload-bearing operator/enrollment actions; the Plus compatibility bridge is the explicit GET-only exception and uses device-grant-scoped capability tokens plus base64url payload with semantic idempotency.'],
    security:{plusCaller:'owner-approved device access grant capability + exact Vercel OIDC at ARM',legacyBridgeCaller:'short-lived ARM-validated bridge session',deviceIdentity:'Ed25519 public-key binding + signed heartbeat + signed outbound fleet channel',upstreamCaller:'Vercel OIDC',envelope:'X25519 + HKDF-SHA256 + AES-256-GCM',replayProtection:true,semanticIdempotency:true,wallAuth:'independent local auth; NetBird optional outer defense',executorUser:'enrolled normal user via platform adapter; Windows DEV uses the signed-in user task'}
  });
};
