module.exports = function handler(req, res) {
  res.setHeader('Cache-Control','no-store'); res.setHeader('X-Robots-Tag','noindex,nofollow,noarchive');
  if(req.method!=='GET') return res.status(405).json({ok:false,error:'method_not_allowed'});
  return res.status(200).json({ok:true,project:'gpt-vps-bridge',version:'0.6.0-dev',purpose:'ChatGPT-facing relay to the owner VPS operator hub',
    activePath:'ChatGPT -> Vercel bridge -> ARM hub -> selected node executor',upstream:'https://mcp.dashboard.thaiduy.store',wall:'https://wall.dashboard.thaiduy.store',
    recoveryDocs:['CURRENT_STATE.md','AI_BRIDGE_GUIDE.md','SESSION_OWNERSHIP_V0_5.md','SESSION_LANES_V0_4.md','HUB_TOPOLOGY_V0_5.md','PRODUCT_PLATFORM_PLAN_V0_6_TO_PUBLIC_PLUGIN.md','DEVICE_PRESENCE_V0_6.md','BRIDGE_V0_3_ARCHITECTURE_PLAN.md','PORTABILITY.md'],
    sessionStart:{agentId:'generate one stable random agent id for this ChatGPT agent/chat, e.g. a_<uuid>',openId:'stable id for one open attempt',open:'/api/operator action=session-open payload={agentId,openId,label,workspace,leasePreset?,leaseMs?}'},
    operatorEndpoints:{capabilities:'/api/operator action=capabilities',devices:'/api/operator action=devices',device:'/api/operator action=device id=<deviceId>',sessionResume:'/api/operator action=session-resume',sessionClose:'/api/operator action=session-close',session:'/api/operator action=session',sessions:'/api/operator action=sessions',sessionStats:'/api/operator action=session-stats',exec:'/api/operator action=exec payload={operationId,script,cwd,timeoutMs,waitMs,sessionId,agentId,note}',job:'/api/operator action=job',output:'/api/operator action=output'},
    readRule:'No static shared Bearer secret is required on v0.6. Session-aware reads carry sessionId+agentId so work renews/audits the correct lane.',
    sessionPolicy:{oneAgentOneLiveSession:true,ownerMismatch:'409 session_owner_mismatch',defaultLeaseMinutes:30,leasePresets:{'30m':30,'1h':60,'3h':180,custom:'leaseMs'},alwaysKeepAlive:'future-only',leaseMinMinutes:5,leaseMaxHours:24,activeJobHold:true,postJobGraceUsesSessionLease:true,maxActiveSessions:5,sessionHistoryDays:7,currentJobTimeoutHours:2},
    deviceModel:{presenceIndependentFromSessions:true,currentDevice:'arm-local',currentNode:'arm',presenceTtlSeconds:90,heartbeatSeconds:30,persistentRegistry:true},
    nodeModel:{currentHub:'arm',currentNodes:['arm'],future:'AMD/HomeLab executors register to ARM hub; Vercel remains connected only to ARM; wall aggregates all node/session lanes.'},
    rules:['One agent owns exactly one live session; a second agentId cannot resume/execute/read another lane.','Every session-aware tool call renews that session lease; running jobs suspend expiry until the last job finishes.','Device presence is independent from operator session lifetime; Wall reads never keep a device or session alive.','v0.6 does not use a static shared Bearer secret at the Vercel boundary; public-product authorization belongs to the account/device/ChatGPT permission plane.','Use Git/worktree discipline for repo concurrency; the operator adds no repo/file locks.','Never put passwords/tokens/private keys/cookies in URL payloads.','GET/query/base64 is legacy bootstrap transport only; v0.6 requires body-safe POST for write/operator payloads.'],
    security:{bridgeCaller:'no static shared Bearer secret on v0.6 development transport',upstreamCaller:'Vercel OIDC',envelope:'X25519 + HKDF-SHA256 + AES-256-GCM',replayProtection:true,semanticIdempotency:true,wallAuth:'independent local auth; NetBird optional outer defense',wallRealtime:'SSE primary + deduplicated replay + 1s missed-event probe',executorUser:'ubuntu'}
  });
};
